#!/usr/bin/env python3
"""Generate HelioseleneCore/ValidationSelene.lean from selene_vectors.json.

Validates the Aeneas-generated Selene group-law translation (point.selene.*)
against independently generated ground-truth vectors: sqrt, projective add /
double / neg (normalized to affine inside the Lean checker via the translated
field inversion), ct_eq, from_xy, plus ad-hoc structural checks and negative
controls. Emits #eval mismatch reports (with per-class wall clock) and one
`native_decide` theorem per vector class.
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
VECTORS = os.path.join(HERE, "selene_vectors.json")
OUT = "/home/user/monero-oxide/crypto/helioselene/aeneas/HelioseleneCore/ValidationSelene.lean"

with open(VECTORS) as f:
    tv = json.load(f)

def b(x):
    return "true" if x else "false"

def pt(triple):
    return f"({triple[0]}, {triple[1]}, {triple[2]})"

def aff(v):
    """Expected output of a projective group-law op: none = identity class."""
    if v["out_inf"]:
        return "none"
    return f"some ({v['out_x']}, {v['out_y']})"

sqrt_rows = [f"({v['a']}, {v['out']}, {b(v['valid'])})" for v in tv["sqrt"]]
add_rows = [f"({pt(v['p1'])}, {pt(v['p2'])}, {aff(v)})" for v in tv["add"]]
dbl_rows = [f"({pt(v['pt'])}, {aff(v)})" for v in tv["double"]]
neg_rows = [f"({pt(v['pt'])}, {v['out_x']}, {v['out_y']})" for v in tv["neg"]]
cteq_rows = [f"({pt(v['p1'])}, {pt(v['p2'])}, {b(v['eq'])})" for v in tv["ct_eq"]]
fxy_rows = [f"({v['x']}, {v['y']}, {b(v['ok'])})" for v in tv["from_xy"]]

total = sum(map(len, [sqrt_rows, add_rows, dbl_rows, neg_rows, cteq_rows, fxy_rows]))

def vec_list(name, ty, rows):
    body = ",\n  ".join(rows)
    return f"def {name} : List ({ty}) := [\n  {body}]\n"

# --- Negative controls: one corrupted vector per class; every checker must
# --- report a mismatch on it (detection is asserted by a native_decide theorem).
sq0 = tv["sqrt"][0]
add0 = next(v for v in tv["add"] if not v["out_inf"])
addinf0 = next(v for v in tv["add"] if v["out_inf"])
dbl0 = next(v for v in tv["double"] if not v["out_inf"])
neg0 = tv["neg"][0]
ct0 = tv["ct_eq"][0]
fxy0 = tv["from_xy"][0]

neg_controls = [
    ("sqrt/out+1",
     f"chkSqrt ({sq0['a']}, {int(sq0['out']) + 1}, {b(sq0['valid'])})"),
    ("sqrt/flag-flip",
     f"chkSqrt ({sq0['a']}, {sq0['out']}, {b(not sq0['valid'])})"),
    ("add/out_x+1",
     f"chkAdd ({pt(add0['p1'])}, {pt(add0['p2'])}, "
     f"some ({int(add0['out_x']) + 1}, {add0['out_y']}))"),
    ("add/inf-flip",
     f"chkAdd ({pt(add0['p1'])}, {pt(add0['p2'])}, none)"),
    ("add/inf-flip'",
     f"chkAdd ({pt(addinf0['p1'])}, {pt(addinf0['p2'])}, "
     f"some ({addinf0['p1'][0]}, {addinf0['p1'][1]}))"),
    ("double/out_y+1",
     f"chkDouble ({pt(dbl0['pt'])}, "
     f"some ({dbl0['out_x']}, {int(dbl0['out_y']) + 1}))"),
    ("neg/out_x+1",
     f"chkNeg ({pt(neg0['pt'])}, {int(neg0['out_x']) + 1}, {neg0['out_y']})"),
    ("ct_eq/flip",
     f"chkCtEq ({pt(ct0['p1'])}, {pt(ct0['p2'])}, {b(not ct0['eq'])})"),
    ("from_xy/flip",
     f"chkFromXy ({fxy0['x']}, {fxy0['y']}, {b(not fxy0['ok'])})"),
]
neg_rows_lean = ",\n  ".join(
    f'("{name}", {expr})' for name, expr in neg_controls)

lean = f"""-- Validation of the Aeneas-generated Selene group-law translation
-- (point.selene.*) against independent ground-truth test vectors
-- ({total} vectors; source: phase-b/selene_vectors.json, generated by
-- phase-b/gen_validation_selene.py — do not edit the vector lists by hand).
--
-- This file is imported by nothing. Like Validation.lean it is allowed to use
-- `native_decide` (the per-theorem native-decide axioms stay quarantined here).
--
-- Conventions (mirroring the Rust code and the extraction models):
--   * SelenePoint is projective (x, y, z); the vectors' group-law outputs are
--     given in AFFINE coordinates (or `none` for the identity class), so the
--     checker normalizes the projective Rust/Lean output via the translated
--     field inversion before comparing.
--   * The identity class is x = 0 (what the translated `is_identity` tests);
--     on the curve this coincides with z = 0 because B is a non-residue (no
--     affine point has x = 0). The checker requires BOTH, so a degenerate
--     (x = 0, z ≠ 0) or (x ≠ 0, z = 0) output is flagged.
--   * `sqrt` returns the EVEN square-root candidate a^((p+1)/4) (negated to
--     even parity) plus an is-QR flag; the candidate is stored in the
--     CtOption even when invalid (subtle semantics).
--   * Choice = Bool, CtOption T = T × Bool (value, is_some).
import HelioseleneCore.Funs

open Aeneas Aeneas.Std Result
open helioselene

namespace HelioseleneValidationSelene

set_option maxRecDepth 4096

/-! ## Harness -/

abbrev F := field.HelioseleneField
abbrev Pt := point.selene.SelenePoint

/-- Embed a natural number (< 2^256) as a field-element representation. -/
def ofN (n : Nat) : F := crypto_bigint.uint.Uint.ofNat 4#usize n

/-- The `Nat` value of a field element (4-limb little-endian `Uint`). -/
def fNat (u : F) : Nat := crypto_bigint.uint.Uint.toNat u

/-- Build a projective Selene point from `Nat` coordinates. -/
def mkPt (v : Nat × Nat × Nat) : Pt := {{ x := ofN v.1, y := ofN v.2.1, z := ofN v.2.2 }}

def mulF := field.HelioseleneField.Insts.CoreOpsArithMulHelioseleneFieldHelioseleneField.mul

/-- Expected affine result of a projective group-law output; `none` = identity. -/
abbrev Aff := Option (Nat × Nat)

/-- Normalize a projective group-law output and compare against ground truth.
    Identity is decided exactly as the translated code does (`is_identity`,
    i.e. x = 0) AND as z = 0 (the on-curve-equivalent predicate); a
    non-identity output is affinized with the translated `invert` (x/z, y/z). -/
def chkProjOut (r : Result Pt) (exp : Aff) : Bool :=
  match r with
  | .ok p =>
    match
      point.selene.SelenePoint.Insts.GroupGroupFieldElementArrayU832.is_identity
        p with
    | .ok idFlag =>
      match exp with
      | none => idFlag && fNat p.z == 0
      | some (ex, ey) =>
        !idFlag && fNat p.z != 0 &&
        (match field.verified.invert.invert p.z with
         | .ok (zinv, true) =>
           (match mulF p.x zinv, mulF p.y zinv with
            | .ok ax, .ok ay => fNat ax == ex && fNat ay == ey
            | _, _ => false)
         | _ => false)
    | _ => false
  | _ => false

/-- `sqrt` returns `CtOption F = F × Bool`: the even root candidate (stored
    even when invalid) and the is-QR flag; both must match. -/
def chkSqrt (v : Nat × Nat × Bool) : Bool :=
  match field.HelioseleneField.Insts.FfField.sqrt (ofN v.1) with
  | .ok (r, flag) => fNat r == v.2.1 && flag == v.2.2
  | _ => false

def chkAdd (v : (Nat × Nat × Nat) × (Nat × Nat × Nat) × Aff) : Bool :=
  chkProjOut
    (point.selene.SelenePoint.Insts.CoreOpsArithAddSelenePointSelenePoint.add
      (mkPt v.1) (mkPt v.2.1)) v.2.2

def chkDouble (v : (Nat × Nat × Nat) × Aff) : Bool :=
  chkProjOut
    (point.selene.SelenePoint.Insts.GroupGroupFieldElementArrayU832.double
      (mkPt v.1)) v.2

def chkNeg (v : (Nat × Nat × Nat) × Nat × Nat) : Bool :=
  chkProjOut
    (point.selene.SelenePoint.Insts.CoreOpsArithNegSelenePoint.neg (mkPt v.1))
    (some (v.2.1, v.2.2))

/-- Projective (class) equality; `Choice = Bool` against the expected flag. -/
def chkCtEq (v : (Nat × Nat × Nat) × (Nat × Nat × Nat) × Bool) : Bool :=
  match
    point.selene.SelenePoint.Insts.SubtleConstantTimeEq.ct_eq (mkPt v.1)
      (mkPt v.2.1) with
  | .ok c => c == v.2.2
  | _ => false

/-- `from_xy` returns `CtOption Pt`; the flag must match `ok` and the stored
    point (kept even when invalid, subtle semantics) must be (x, y, 1). -/
def chkFromXy (v : Nat × Nat × Bool) : Bool :=
  match point.selene.SelenePoint.from_xy (ofN v.1) (ofN v.2.1) with
  | .ok (p, flag) =>
    flag == v.2.2 && fNat p.x == v.1 && fNat p.y == v.2.1 && fNat p.z == 1
  | _ => false

/-- Indices of failing vectors (empty ↔ all pass). -/
def failIdxs {{α}} [Inhabited α] (chk : α → Bool) (vs : List α) : List Nat :=
  (List.range vs.length).filter (fun i => !chk vs[i]!)

/-- Run one vector class in IO, reporting failures and interpreted wall clock. -/
def run {{α}} [Inhabited α] (label : String) (chk : α → Bool) (vs : List α) :
    IO Unit := do
  -- `IO.lazyPure` keeps the checker run (a) from being lifted out as a closed
  -- term and pre-evaluated, and (b) from being sunk below the second timestamp
  -- (both compiler transformations make naive timers report 0).
  let vs ← IO.lazyPure (fun _ => vs)
  let t0 ← IO.monoMsNow
  let bad ← IO.lazyPure (fun _ => failIdxs chk vs)
  let t1 ← IO.monoMsNow
  if bad.isEmpty then
    IO.println s!"{{label}}: {{vs.length}}/{{vs.length}} ok ({{t1 - t0}} ms interpreted)"
  else
    IO.println s!"{{label}}: FAIL at indices {{bad}} of {{vs.length}} ({{t1 - t0}} ms)"

/-! ## Ground-truth vectors (independent of the Rust/Lean implementation) -/

/-- p = {tv['p']} -/
def pVal : Nat := {tv['p']}

{vec_list("sqrtVecs", "Nat × Nat × Bool", sqrt_rows)}
{vec_list("addVecs", "(Nat × Nat × Nat) × (Nat × Nat × Nat) × Aff", add_rows)}
{vec_list("doubleVecs", "(Nat × Nat × Nat) × Aff", dbl_rows)}
{vec_list("negVecs", "(Nat × Nat × Nat) × Nat × Nat", neg_rows)}
{vec_list("ctEqVecs", "(Nat × Nat × Nat) × (Nat × Nat × Nat) × Bool", cteq_rows)}
{vec_list("fromXyVecs", "Nat × Nat × Bool", fxy_rows)}
/-! ## Ad-hoc structural checks -/

/-- The translated curve constants match the independent ground truth. -/
def chkConstants : Bool :=
  match point.selene.G_X, point.selene.G_Y, point.selene.B with
  | .ok gx, .ok gy, .ok bb =>
    fNat gx == {tv['G_X']} &&
    fNat gy == {tv['G_Y']} &&
    fNat bb == {tv['B']}
  | _, _, _ => false

/-- The generator satisfies the curve equation: G_Y² = curve_equation(G_X),
    with z = 1 (both sides computed by the translated code). -/
def chkGeneratorOnCurve : Bool :=
  match point.selene.G with
  | .ok g =>
    (match field.verified.square g.y, point.selene.curve_equation g.x with
     | .ok l, .ok r => fNat l == fNat r && fNat g.z == 1
     | _, _ => false)
  | _ => false

/-- B is a quadratic non-residue (so no affine point has x = 0, which makes the
    `is_identity` x = 0 test sound): the translated sqrt flags it invalid. -/
def chkBNonResidue : Bool :=
  match point.selene.B with
  | .ok bb =>
    (match field.HelioseleneField.Insts.FfField.sqrt bb with
     | .ok (_, flag) => flag == false
     | _ => false)
  | _ => false

/-- `is_identity identity = true` and `identity = (0, 1, 0)`. -/
def chkIdentityIsIdentity : Bool :=
  match
    point.selene.SelenePoint.Insts.GroupGroupFieldElementArrayU832.identity with
  | .ok id =>
    (match
       point.selene.SelenePoint.Insts.GroupGroupFieldElementArrayU832.is_identity
         id with
     | .ok c => c && fNat id.x == 0 && fNat id.y == 1 && fNat id.z == 0
     | _ => false)
  | _ => false

/-- `is_identity generator = false`. -/
def chkGeneratorNotIdentity : Bool :=
  match
    point.selene.SelenePoint.Insts.GroupGroupFieldElementArrayU832.generator with
  | .ok g =>
    (match
       point.selene.SelenePoint.Insts.GroupGroupFieldElementArrayU832.is_identity
         g with
     | .ok c => !c
     | _ => false)
  | _ => false

def adHocChecks : List (String × Bool) := [
  ("constants", chkConstants),
  ("generator-on-curve", chkGeneratorOnCurve),
  ("B-non-residue", chkBNonResidue),
  ("identity-is-identity", chkIdentityIsIdentity),
  ("generator-not-identity", chkGeneratorNotIdentity)]

/-! ## Negative controls

One corrupted vector per class (expected value bumped / flag flipped /
identity-class flag flipped both ways). Every checker MUST report `false` on
its corrupted vector — this shows the harness actually detects mismatches and
the positive theorems below are not vacuous. -/

def negControls : List (String × Bool) := [
  {neg_rows_lean}]

/-! ## Interpreted runs (mismatch localization + per-class timing) -/

#eval run "selene sqrt   " chkSqrt sqrtVecs
#eval run "selene add    " chkAdd addVecs
#eval run "selene double " chkDouble doubleVecs
#eval run "selene neg    " chkNeg negVecs
#eval run "selene ct_eq  " chkCtEq ctEqVecs
#eval run "selene from_xy" chkFromXy fromXyVecs
#eval run "selene ad-hoc " (fun (c : String × Bool) => c.2) adHocChecks
#eval run "selene negctrl" (fun (c : String × Bool) => !c.2) negControls

/-! ## Machine-checked theorems (`native_decide`; one
`validationSelene_*._native.native_decide.ax_1_1` axiom each) -/

theorem validationSelene_sqrt : sqrtVecs.all chkSqrt = true := by native_decide
theorem validationSelene_add : addVecs.all chkAdd = true := by native_decide
theorem validationSelene_double : doubleVecs.all chkDouble = true := by
  native_decide
theorem validationSelene_neg : negVecs.all chkNeg = true := by native_decide
theorem validationSelene_ct_eq : ctEqVecs.all chkCtEq = true := by native_decide
theorem validationSelene_from_xy : fromXyVecs.all chkFromXy = true := by
  native_decide
theorem validationSelene_adhoc : adHocChecks.all (·.2) = true := by
  native_decide
/-- Every deliberately corrupted vector is detected (checker returns false). -/
theorem validationSelene_negative_controls :
    negControls.all (fun c => !c.2) = true := by native_decide

end HelioseleneValidationSelene
"""

with open(OUT, "w") as f:
    f.write(lean)

print(f"wrote {OUT}: {total} vectors "
      f"(sqrt {len(sqrt_rows)}, add {len(add_rows)}, double {len(dbl_rows)}, "
      f"neg {len(neg_rows)}, ct_eq {len(cteq_rows)}, from_xy {len(fxy_rows)}), "
      f"{len(neg_controls)} negative controls")
