#!/usr/bin/env python3
"""Generate HelioseleneCore/Validation.lean from test_vectors.json.

Emits a machine-checked validation file: vector lists (Nat tuples), Bool checkers
that run the Aeneas-generated model, #eval mismatch reports (with per-class wall
clock), and one `native_decide` theorem per vector class.
"""
import json, sys, os

HERE = os.path.dirname(os.path.abspath(__file__))
VECTORS = os.path.join(HERE, "test_vectors.json")
OUT = "/home/user/monero-oxide/crypto/helioselene/aeneas/HelioseleneCore/Validation.lean"

with open(VECTORS) as f:
    tv = json.load(f)

def pair_list(name, ty, rows):
    body = ",\n  ".join(rows)
    return f"def {name} : List ({ty}) := [\n  {body}]\n"

red256 = [f"({v['in']}, {v['out']})" for v in tv["red256"]]
red512 = [f"({v['lo']}, {v['hi']}, {v['out']})" for v in tv["red512"]]
add    = [f"({v['a']}, {v['b']}, {v['out']})" for v in tv["ops"]["add"]]
sub    = [f"({v['a']}, {v['b']}, {v['out']})" for v in tv["ops"]["sub"]]
mul    = [f"({v['a']}, {v['b']}, {v['out']})" for v in tv["ops"]["mul"]]
neg    = [f"({v['a']}, {v['out']})" for v in tv["ops"]["neg"]]
dbl    = [f"({v['a']}, {v['out']})" for v in tv["ops"]["double"]]
sqr    = [f"({v['a']}, {v['out']})" for v in tv["ops"]["square"]]
inv    = [f"({v['a']}, {v['out']}, {'true' if v['valid'] else 'false'})" for v in tv["invert"]]
frep   = [f"({v['bytes_le_val']}, {'true' if v['ok'] else 'false'})" for v in tv["from_repr"]]

total = sum(map(len, [red256, red512, add, sub, mul, neg, dbl, sqr, inv, frep]))

lean = f"""-- Validation of the computable Aeneas-generated model against independent
-- ground-truth test vectors ({total} vectors; source: phase-b/test_vectors.json,
-- generated by phase-b/gen_validation.py — do not edit the vector lists by hand).
--
-- This file is imported by nothing. It is the ONLY file allowed to use
-- `native_decide` (axiom `Lean.ofReduceBool` stays quarantined here).
import HelioseleneCore.Funs

open Aeneas Aeneas.Std Result
open helioselene

namespace HelioseleneValidation

set_option maxRecDepth 4096

/-! ## Harness -/

/-- Field elements are 4-limb little-endian `Uint`s. -/
abbrev F := field.HelioseleneField

/-- Embed a natural number (< 2^256) as a field-element representation. -/
def ofN (n : Nat) : F := crypto_bigint.uint.Uint.ofNat 4#usize n

/-- Extract the `Nat` value of an `ok` result; `none` on `fail`/`div`. -/
def resNat (r : Result F) : Option Nat :=
  match r with
  | .ok u => some (crypto_bigint.uint.Uint.toNat u)
  | _ => none

/-- The 32-byte little-endian encoding of `n` (< 2^256), as `from_repr` input. -/
def bytesLE (n : Nat) : Array Std.U8 32#usize :=
  Array.make 32#usize
    (List.ofFn (fun (i : Fin 32) => HelioseleneModel.byteOfNat (n >>> (8 * i.val))))

def chkRed256 (v : Nat × Nat) : Bool :=
  resNat (field.verified.red.red256 (ofN v.1)) == some v.2

def chkRed512 (v : Nat × Nat × Nat) : Bool :=
  resNat (field.verified.red.red512 (ofN v.1, ofN v.2.1)) == some v.2.2

def chkAdd (v : Nat × Nat × Nat) : Bool :=
  resNat
    (field.HelioseleneField.Insts.CoreOpsArithAddHelioseleneFieldHelioseleneField.add
      (ofN v.1) (ofN v.2.1)) == some v.2.2

def chkSub (v : Nat × Nat × Nat) : Bool :=
  resNat
    (field.HelioseleneField.Insts.CoreOpsArithSubHelioseleneFieldHelioseleneField.sub
      (ofN v.1) (ofN v.2.1)) == some v.2.2

def chkMul (v : Nat × Nat × Nat) : Bool :=
  resNat
    (field.HelioseleneField.Insts.CoreOpsArithMulHelioseleneFieldHelioseleneField.mul
      (ofN v.1) (ofN v.2.1)) == some v.2.2

def chkNeg (v : Nat × Nat) : Bool :=
  resNat (field.HelioseleneField.Insts.CoreOpsArithNegHelioseleneField.neg (ofN v.1))
    == some v.2

def chkDouble (v : Nat × Nat) : Bool :=
  resNat (field.verified.double (ofN v.1)) == some v.2

def chkSquare (v : Nat × Nat) : Bool :=
  resNat (field.verified.square (ofN v.1)) == some v.2

/-- `invert` returns `CtOption F = F × Bool`; both the value and the validity flag
    must match the ground truth. -/
def chkInvert (v : Nat × Nat × Bool) : Bool :=
  match field.verified.invert.invert (ofN v.1) with
  | .ok (u, flag) => crypto_bigint.uint.Uint.toNat u == v.2.1 && flag == v.2.2
  | _ => false

/-- `from_repr` returns `CtOption F`; the flag must match `ok`, and the stored value
    must equal the little-endian byte value (subtle stores it even when invalid). -/
def chkFromRepr (v : Nat × Bool) : Bool :=
  match field.verified.from_repr (bytesLE v.1) with
  | .ok (u, flag) => flag == v.2 && crypto_bigint.uint.Uint.toNat u == v.1
  | _ => false

/-- Indices of failing vectors (empty ↔ all pass). -/
def failIdxs {{α}} [Inhabited α] (chk : α → Bool) (vs : List α) : List Nat :=
  (List.range vs.length).filter (fun i => !chk vs[i]!)

/-- Run one vector class in IO, reporting failures and interpreted wall clock. -/
def run {{α}} [Inhabited α] (label : String) (chk : α → Bool) (vs : List α) :
    IO Unit := do
  -- `IO.lazyPure` keeps the checker run (a) from being lifted out as a closed
  -- term and pre-evaluated, and (b) from being sunk below the second timestamp
  -- (both compiler transformations make naive timers report 0).
  let vs ← IO.lazyPure (fun _ => vs)
  let t0 ← IO.monoMsNow
  let bad ← IO.lazyPure (fun _ => failIdxs chk vs)
  let t1 ← IO.monoMsNow
  if bad.isEmpty then
    IO.println s!"{{label}}: {{vs.length}}/{{vs.length}} ok ({{t1 - t0}} ms interpreted)"
  else
    IO.println s!"{{label}}: FAIL at indices {{bad}} of {{vs.length}} ({{t1 - t0}} ms)"

/-! ## Ground-truth vectors (independent of the Rust/Lean implementation) -/

/-- p = {tv['p']} -/
def pVal : Nat := {tv['p']}

{pair_list("red256Vecs", "Nat × Nat", red256)}
{pair_list("red512Vecs", "Nat × Nat × Nat", red512)}
{pair_list("addVecs", "Nat × Nat × Nat", add)}
{pair_list("subVecs", "Nat × Nat × Nat", sub)}
{pair_list("mulVecs", "Nat × Nat × Nat", mul)}
{pair_list("negVecs", "Nat × Nat", neg)}
{pair_list("doubleVecs", "Nat × Nat", dbl)}
{pair_list("squareVecs", "Nat × Nat", sqr)}
{pair_list("invertVecs", "Nat × Nat × Bool", inv)}
{pair_list("fromReprVecs", "Nat × Bool", frep)}

/-! ## Interpreted runs (mismatch localization + per-class timing) -/

#eval run "red256   " chkRed256 red256Vecs
#eval run "red512   " chkRed512 red512Vecs
#eval run "add      " chkAdd addVecs
#eval run "sub      " chkSub subVecs
#eval run "mul      " chkMul mulVecs
#eval run "neg      " chkNeg negVecs
#eval run "double   " chkDouble doubleVecs
#eval run "square   " chkSquare squareVecs
#eval run "invert   " chkInvert invertVecs
#eval run "from_repr" chkFromRepr fromReprVecs

/-! ## Machine-checked theorems (`native_decide`; axiom `Lean.ofReduceBool`) -/

theorem validation_red256 : red256Vecs.all chkRed256 = true := by native_decide
theorem validation_red512 : red512Vecs.all chkRed512 = true := by native_decide
theorem validation_add : addVecs.all chkAdd = true := by native_decide
theorem validation_sub : subVecs.all chkSub = true := by native_decide
theorem validation_mul : mulVecs.all chkMul = true := by native_decide
theorem validation_neg : negVecs.all chkNeg = true := by native_decide
theorem validation_double : doubleVecs.all chkDouble = true := by native_decide
theorem validation_square : squareVecs.all chkSquare = true := by native_decide
theorem validation_invert : invertVecs.all chkInvert = true := by native_decide
theorem validation_from_repr : fromReprVecs.all chkFromRepr = true := by
  native_decide

end HelioseleneValidation
"""

with open(OUT, "w") as f:
    f.write(lean)

print(f"wrote {OUT}: {total} vectors "
      f"(red256={len(red256)}, red512={len(red512)}, add={len(add)}, sub={len(sub)}, "
      f"mul={len(mul)}, neg={len(neg)}, double={len(dbl)}, square={len(sqr)}, "
      f"invert={len(inv)}, from_repr={len(frep)})")
