-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [helioselene]: external functions.
-- Instantiated from the template: the external functions are given concrete computable models.
import Aeneas
import HelioseleneCore.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open helioselene

/-! ## Model helpers

`crypto_bigint.uint.Uint LIMBS` is instantiated (TypesExternal.lean) as the little-endian
limb vector `Aeneas.Std.Array Aeneas.Std.U64 LIMBS`, `subtle.Choice` as `Bool` and
`subtle.CtOption T` as `T × Bool`. The helpers below convert between limb vectors and
natural numbers; every arithmetic model is then defined as `ofNat` of the exact `Nat`
computation. -/

namespace HelioseleneModel

/-- Truncate a natural number into a 64-bit limb (mod 2^64). -/
def limbOfNat (n : Nat) : Std.U64 := ⟨BitVec.ofNat _ n⟩

/-- Truncate a natural number into a byte (mod 2^8). -/
def byteOfNat (n : Nat) : Std.U8 := ⟨BitVec.ofNat _ n⟩

/-- The all-ones limb 2^64 - 1 (the `Limb::MAX` borrow/carry mask). -/
def limbAllOnes : Std.U64 := ⟨BitVec.allOnes _⟩

/-- Value of an ASCII hex digit (`0-9a-fA-F`), or `none` for any other byte. -/
def hexDigit? (b : Std.U8) : Option Nat :=
  if 48 ≤ b.val ∧ b.val ≤ 57 then some (b.val - 48)        -- '0'..'9'
  else if 97 ≤ b.val ∧ b.val ≤ 102 then some (b.val - 87)  -- 'a'..'f'
  else if 65 ≤ b.val ∧ b.val ≤ 70 then some (b.val - 55)   -- 'A'..'F'
  else none

/-- Parse a big-endian ASCII hex byte string to a natural number; `none` if any byte is not
    a hex digit. -/
def parseBeHex? (bs : List Std.U8) : Option Nat :=
  bs.foldl
    (fun acc b =>
      match acc, hexDigit? b with
      | some a, some d => some (a * 16 + d)
      | _, _ => none)
    (some 0)

/-- The natural number denoted by a little-endian byte list. -/
def leBytesToNat (bs : List Std.U8) : Nat :=
  bs.foldr (fun b acc => acc * 256 + b.val) 0

end HelioseleneModel

/-- The natural number denoted by a `Uint` (little-endian limb order, limb i has weight
    2^(64·i)). Always < 2^(64·LIMBS). -/
def crypto_bigint.uint.Uint.toNat {LIMBS : Std.Usize}
  (u : crypto_bigint.uint.Uint LIMBS) : Nat :=
  u.val.foldr (fun (l : Std.U64) (acc : Nat) => acc * 2 ^ 64 + l.val) 0

/-- The `LIMBS`-limb little-endian decomposition of `n mod 2^(64·LIMBS)`. -/
def crypto_bigint.uint.Uint.ofNat (LIMBS : Std.Usize) (n : Nat) :
  crypto_bigint.uint.Uint LIMBS :=
  Array.make LIMBS
    (List.ofFn (fun (i : Fin LIMBS.val) => HelioseleneModel.limbOfNat (n >>> (64 * i.val))))

/-- **Rust:** `crypto_bigint::Limb::wrapping_add` — function (foreign: crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/limb/add.rs:26-28 (crate source):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/limb/add.rs.html#26-28

    Single-limb wrapping addition: returns `Limb(self.0.wrapping_add(rhs.0))`, i.e. a + b
    mod 2^64, silently discarding any carry out of the top bit.

    Used once in the translation, by `field.verified.invert.invert.step_loop3.body` (the
    `for l in 0 .. U128::LIMBS` modulus-addition loop of `invert`'s `step`,
    src/field/verified/invert.rs line 154): `modulus_instances.wrapping_add(carry)` folds the
    0/1 loop carry into the selected modulus limb; the low limbs of the modulus are not full,
    so no carry is lost there.

    Model: bit-vector addition mod 2^64; `ok ⟨a.bv + b.bv⟩`.

    Aeneas metadata:
    [crypto_bigint::limb::add::{crypto_bigint::limb::Limb}::wrapping_add]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/limb/add.rs', lines 26:4-26:55 -/
@[rust_fun
  "crypto_bigint::limb::add::{crypto_bigint::limb::Limb}::wrapping_add"]
def crypto_bigint.limb.add.Limb.wrapping_add
  :
  crypto_bigint.limb.Limb → crypto_bigint.limb.Limb → Result
    crypto_bigint.limb.Limb :=
  fun a b => ok ⟨a.bv + b.bv⟩

/-- **Rust:** `<crypto_bigint::Limb as core::ops::BitAnd>::bitand` — trait-impl method
    (foreign: crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/limb/bit_and.rs:14-21 (method at line 18):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/limb/bit_and.rs.html#14-21

    Bitwise AND of two 64-bit limbs, `Limb(self.0 & rhs.0)`; this is what the `&` operator on
    limbs resolves to. Combined with 0/all-ones masks it is the constant-time keep-or-zero
    primitive of the whole field implementation.

    Used by `select_word` (`a ^ ((a ^ b) & choice)`, src/field/verified/mod.rs:44-47), by the
    mask-and-add folding steps of `red256`/`red512` (masking `MODULUS_255_DISTANCE` and
    `TWO_MODULUS_255_DISTANCE` limbs with carry masks, src/field/verified/red.rs), by
    `invert`'s `step` (odd/borrow masks), and by `from_repr::reduced`.

    Model: bit-vector AND; `ok ⟨a.bv &&& b.bv⟩`.

    Aeneas metadata:
    [crypto_bigint::limb::bit_and::{impl core::ops::bit::BitAnd<crypto_bigint::limb::Limb, crypto_bigint::limb::Limb> for crypto_bigint::limb::Limb}::bitand]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/limb/bit_and.rs', lines 18:4-18:46 -/
@[rust_fun
  "crypto_bigint::limb::bit_and::{core::ops::bit::BitAnd<crypto_bigint::limb::Limb, crypto_bigint::limb::Limb, crypto_bigint::limb::Limb>}::bitand"]
def crypto_bigint.limb.Limb.Insts.CoreOpsBitBitAndLimbLimb.bitand
  :
  crypto_bigint.limb.Limb → crypto_bigint.limb.Limb → Result
    crypto_bigint.limb.Limb :=
  fun a b => ok ⟨a.bv &&& b.bv⟩

/-- **Rust:** `<crypto_bigint::Limb as core::ops::Not>::not` — trait-impl method
    (foreign: crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/limb/bit_not.rs:13-19 (method at line 16):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/limb/bit_not.rs.html#13-19

    Bitwise complement of a 64-bit limb, `Limb(!self.0)`; this is what the unary `!` operator
    on limbs resolves to. On a 0/all-ones mask it flips the selection condition.

    Used once, in `invert`'s `step`: `add_two_modulus = v_u_sub_u_v_neg & (!result_is_odd)`
    (src/field/verified/invert.rs:134), which decides whether a second modulus instance must
    be added so the intermediate value stays even before halving.

    Model: bit-vector complement; `ok ⟨~~~a.bv⟩`.

    Aeneas metadata:
    [crypto_bigint::limb::bit_not::{impl core::ops::bit::Not<crypto_bigint::limb::Limb> for crypto_bigint::limb::Limb}::not]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/limb/bit_not.rs', lines 16:4-16:41 -/
@[rust_fun
  "crypto_bigint::limb::bit_not::{core::ops::bit::Not<crypto_bigint::limb::Limb, crypto_bigint::limb::Limb>}::not"]
def crypto_bigint.limb.Limb.Insts.CoreOpsBitNotLimb.not
  : crypto_bigint.limb.Limb → Result crypto_bigint.limb.Limb :=
  fun a => ok ⟨~~~a.bv⟩

/-- **Rust:** `<crypto_bigint::Limb as core::ops::BitOr>::bitor` — trait-impl method
    (foreign: crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/limb/bit_or.rs:13-19 (method at line 16):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/limb/bit_or.rs.html#13-19

    Bitwise OR of two 64-bit limbs, `Limb(self.0 | rhs.0)`; this is what the `|` operator on
    limbs resolves to.

    Used by `is_zero` to OR-fold all four limbs into one accumulator so a single constant-time
    comparison with zero suffices (src/field/verified/mod.rs:123-129), by `invert`'s `step`
    (`add_one_modulus = v_u_sub_u_v_neg | result_is_odd` and re-inserting the deferred top bit,
    src/field/verified/invert.rs:136 and 164-165), and by `from_repr::reduced`'s final check
    (src/field/verified/mod.rs:151).

    Model: bit-vector OR; `ok ⟨a.bv ||| b.bv⟩`.

    Aeneas metadata:
    [crypto_bigint::limb::bit_or::{impl core::ops::bit::BitOr<crypto_bigint::limb::Limb, crypto_bigint::limb::Limb> for crypto_bigint::limb::Limb}::bitor]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/limb/bit_or.rs', lines 16:4-16:45 -/
@[rust_fun
  "crypto_bigint::limb::bit_or::{core::ops::bit::BitOr<crypto_bigint::limb::Limb, crypto_bigint::limb::Limb, crypto_bigint::limb::Limb>}::bitor"]
def crypto_bigint.limb.Limb.Insts.CoreOpsBitBitOrLimbLimb.bitor
  :
  crypto_bigint.limb.Limb → crypto_bigint.limb.Limb → Result
    crypto_bigint.limb.Limb :=
  fun a b => ok ⟨a.bv ||| b.bv⟩

/-- **Rust:** `<crypto_bigint::Limb as core::ops::BitXor>::bitxor` — trait-impl method
    (foreign: crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/limb/bit_xor.rs:13-19 (method at line 16):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/limb/bit_xor.rs.html#13-19

    Bitwise XOR of two 64-bit limbs, `Limb(self.0 ^ rhs.0)`; this is what the `^` operator on
    limbs resolves to. XOR against an all-ones mask is a conditional logical NOT, the core of
    branch-free selection and negation.

    Used by `select_word`'s constant-time select `a ^ ((a ^ b) & choice)`
    (src/field/verified/mod.rs:44-47) and heavily in `invert`'s `step`: conditional negation
    of `a_sub_b` and `u_sub_v` (`x ^ mask` plus carry-in), and the XOR'd-constant trick
    `(MODULUS[l] & add_one) ^ (MODULUS_XOR_TWO_MODULUS[l] & add_two)`
    (src/field/verified/invert.rs).

    Model: bit-vector XOR; `ok ⟨a.bv ^^^ b.bv⟩`.

    Aeneas metadata:
    [crypto_bigint::limb::bit_xor::{impl core::ops::bit::BitXor<crypto_bigint::limb::Limb, crypto_bigint::limb::Limb> for crypto_bigint::limb::Limb}::bitxor]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/limb/bit_xor.rs', lines 16:4-16:46 -/
@[rust_fun
  "crypto_bigint::limb::bit_xor::{core::ops::bit::BitXor<crypto_bigint::limb::Limb, crypto_bigint::limb::Limb, crypto_bigint::limb::Limb>}::bitxor"]
def crypto_bigint.limb.Limb.Insts.CoreOpsBitBitXorLimbLimb.bitxor
  :
  crypto_bigint.limb.Limb → crypto_bigint.limb.Limb → Result
    crypto_bigint.limb.Limb :=
  fun a b => ok ⟨a.bv ^^^ b.bv⟩

/-- **Rust:** `<crypto_bigint::Limb as subtle::ConstantTimeEq>::ct_eq` — trait-impl method
    (foreign: crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/limb/cmp.rs:70-75 (method at line 72):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/limb/cmp.rs.html#70-75

    Constant-time equality of two 64-bit limbs, returning a `subtle::Choice` (1 if equal, 0
    otherwise). Delegates to subtle's `u64` implementation, which reduces `a XOR b` to a 0/1
    flag with arithmetic only — no data-dependent branch.

    Used by `is_zero` (`all.ct_eq(&Limb::ZERO)` after OR-folding all limbs,
    src/field/verified/mod.rs:123-129) and by `from_repr::reduced`, whose final
    `.ct_eq(&Limb::ZERO)` decides whether the candidate encoding is fully reduced
    (src/field/verified/mod.rs:151).

    Model: decidable equality of the limb values; `ok (a.val == b.val)` (Choice = Bool).

    Aeneas metadata:
    [crypto_bigint::limb::cmp::{impl subtle::ConstantTimeEq for crypto_bigint::limb::Limb}::ct_eq]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/limb/cmp.rs', lines 72:4-72:43 -/
@[rust_fun
  "crypto_bigint::limb::cmp::{subtle::ConstantTimeEq<crypto_bigint::limb::Limb>}::ct_eq"]
def crypto_bigint.limb.Limb.Insts.SubtleConstantTimeEq.ct_eq
  :
  crypto_bigint.limb.Limb → crypto_bigint.limb.Limb → Result subtle.Choice :=
  fun a b => ok (a.val == b.val)

/-- **Rust:** `crypto_bigint::Limb::mac` — function (foreign: crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/limb/mul.rs:10-17 (crate source):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/limb/mul.rs.html#10-17

    Multiply-accumulate with carry: computes `self + (b * c) + carry` exactly in 128-bit
    arithmetic and returns the pair (low word, high word). This is the classic inner step of
    schoolbook multiprecision multiplication; the 128-bit intermediate cannot overflow.

    Used only by `red512`'s two folding passes (src/field/verified/red.rs:50-53 and 91-94;
    Lean loops `red512_loop0`/`red512_loop4` with their inner loops): each limb of the upper
    256 bits is multiplied by the limbs of `TWO_MODULUS_255_DISTANCE` = 2^256 - 2p and
    accumulated onto the low limbs — the multiplication step of the Crandall-style reduction.

    Model: r := a.val + b.val·c.val + carry.val (exact in Nat; always < 2^128 since each
    input is < 2^64); `ok (low 64 bits of r, high 64 bits of r)`.

    Aeneas metadata:
    [crypto_bigint::limb::mul::{crypto_bigint::limb::Limb}::mac]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/limb/mul.rs', lines 10:4-10:73 -/
@[rust_fun "crypto_bigint::limb::mul::{crypto_bigint::limb::Limb}::mac"]
def crypto_bigint.limb.mul.Limb.mac
  :
  crypto_bigint.limb.Limb → crypto_bigint.limb.Limb →
    crypto_bigint.limb.Limb → crypto_bigint.limb.Limb → Result
    (crypto_bigint.limb.Limb × crypto_bigint.limb.Limb) :=
  fun a b c carry =>
    let r := a.val + b.val * c.val + carry.val
    ok (HelioseleneModel.limbOfNat r, HelioseleneModel.limbOfNat (r >>> 64))

/-- **Rust:** `crypto_bigint::Limb::wrapping_neg` — function (foreign: crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/limb/neg.rs:17-19 (crate source):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/limb/neg.rs.html#17-19

    Two's-complement negation mod 2^64: returns `0 - x` wrapped. Applied to a 0/1 carry or
    borrow bit it yields 0 or 0xFFFF_FFFF_FFFF_FFFF — the standard way of expanding a flag
    into a full-width mask for constant-time selection.

    Used by `red256` (`high_bit.wrapping_neg()`, src/field/verified/red.rs:10), by `red512`
    (carry masks at red.rs:74 and 104), and by `invert`'s `step` (the `a_is_odd`, `a_lt_b`,
    `u_sub_v_neg` and `result_is_odd` masks, src/field/verified/invert.rs).

    Model: bit-vector negation mod 2^64; `ok ⟨-a.bv⟩`.

    Aeneas metadata:
    [crypto_bigint::limb::neg::{crypto_bigint::limb::Limb}::wrapping_neg]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/limb/neg.rs', lines 17:4-17:43 -/
@[rust_fun
  "crypto_bigint::limb::neg::{crypto_bigint::limb::Limb}::wrapping_neg"]
def crypto_bigint.limb.neg.Limb.wrapping_neg
  : crypto_bigint.limb.Limb → Result crypto_bigint.limb.Limb :=
  fun a => ok ⟨-a.bv⟩

/-- **Rust:** `<crypto_bigint::Limb as core::ops::Shl<usize>>::shl` — trait-impl method
    (foreign: crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/limb/shl.rs:24-31 (method at line 28):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/limb/shl.rs.html#24-31

    Left shift of a limb by a `usize` amount (`<<` operator); delegates to the inherent
    `Limb::shl` (`self.0 << rhs.0`), which panics if the shift is >= `Limb::BITS`. The
    translation only shifts by the constant `Limb::BITS - 1` = 63, so no panic can occur.

    Model: `ok ⟨a.bv <<< s.val⟩` when s.val < 64, `fail panic` otherwise (matching the Rust
    panic on oversized shifts).

    Aeneas metadata:
    [crypto_bigint::limb::shl::{impl core::ops::bit::Shl<usize, crypto_bigint::limb::Limb> for crypto_bigint::limb::Limb}::shl]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/limb/shl.rs', lines 28:4-28:44 -/
@[rust_fun
  "crypto_bigint::limb::shl::{core::ops::bit::Shl<crypto_bigint::limb::Limb, usize, crypto_bigint::limb::Limb>}::shl"]
def crypto_bigint.limb.Limb.Insts.CoreOpsBitShlUsizeLimb.shl
  : crypto_bigint.limb.Limb → Std.Usize → Result crypto_bigint.limb.Limb :=
  fun a s => if s.val < 64 then ok ⟨a.bv <<< s.val⟩ else fail Error.panic

/-- **Rust:** `<crypto_bigint::Limb as core::ops::Shr<usize>>::shr` — trait-impl method
    (foreign: crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/limb/shr.rs:24-31 (method at line 28):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/limb/shr.rs.html#24-31

    Right shift of a limb by a `usize` amount (`>>` operator); delegates to the inherent
    `Limb::shr` (`self.0 >> rhs.0`), which panics if the shift is >= `Limb::BITS`. The
    translation only uses constant shifts (1 and 63), so no panic can occur.

    Used by `red256` to extract bit 255 of the input,
    `a.as_limbs()[U256::LIMBS - 1] >> (Limb::BITS - 1)`, and to build the clear-top-bit mask
    `Limb::MAX >> 1` (src/field/verified/red.rs:10-11).

    Model: `ok ⟨a.bv >>> s.val⟩` when s.val < 64, `fail panic` otherwise (matching the Rust
    panic on oversized shifts).

    Aeneas metadata:
    [crypto_bigint::limb::shr::{impl core::ops::bit::Shr<usize, crypto_bigint::limb::Limb> for crypto_bigint::limb::Limb}::shr]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/limb/shr.rs', lines 28:4-28:44 -/
@[rust_fun
  "crypto_bigint::limb::shr::{core::ops::bit::Shr<crypto_bigint::limb::Limb, usize, crypto_bigint::limb::Limb>}::shr"]
def crypto_bigint.limb.Limb.Insts.CoreOpsBitShrUsizeLimb.shr
  : crypto_bigint.limb.Limb → Std.Usize → Result crypto_bigint.limb.Limb :=
  fun a s => if s.val < 64 then ok ⟨a.bv >>> s.val⟩ else fail Error.panic

/-- **Rust:** `<crypto_bigint::Limb as core::clone::Clone>::clone` (derived) — trait-impl
    method (foreign: crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/limb.rs:63 (`#[derive(Copy, Clone, Default, Hash)]`):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/limb.rs.html#63

    The compiler-derived `Clone::clone` for `Limb`: returns a bitwise copy of the wrapped
    64-bit word. `Limb` is `Copy`, so cloning is trivial and has no side effects.

    Referenced only by the trait-instance record `crypto_bigint.limb.Limb.Insts.CoreCloneClone`
    in Funs.lean, which supplies the `Clone` dictionary wherever the translated field code
    clones limb values.

    Model: the identity; `ok a`.

    Aeneas metadata:
    [crypto_bigint::limb::{impl core::clone::Clone for crypto_bigint::limb::Limb}::clone]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/limb.rs', lines 63:15-63:20 -/
@[rust_fun
  "crypto_bigint::limb::{core::clone::Clone<crypto_bigint::limb::Limb>}::clone"]
def crypto_bigint.limb.Limb.Insts.CoreCloneClone.clone
  : crypto_bigint.limb.Limb → Result crypto_bigint.limb.Limb :=
  fun a => ok a

/-- **Rust:** `crypto_bigint::Limb::ZERO` — constant (foreign: crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/limb.rs:69 (crate source):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/limb.rs.html#69

    The constant `Limb(0)`. Aeneas models Rust constants as monadic values, hence the
    `Result crypto_bigint.limb.Limb` type.

    Used as the initial carry/borrow/accumulator value throughout the translated field code:
    `is_zero`, `sub_value`, `red256`, `red512`, `invert`'s `step`, and `from_repr::reduced`.

    Model: `ok 0#u64`.

    Aeneas metadata:
    [crypto_bigint::limb::{crypto_bigint::limb::Limb}::ZERO]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/limb.rs', lines 69:4-69:24 -/
@[rust_const "crypto_bigint::limb::{crypto_bigint::limb::Limb}::ZERO"]
def crypto_bigint.limb.Limb.ZERO : Result crypto_bigint.limb.Limb :=
  ok 0#u64

/-- **Rust:** `crypto_bigint::Limb::ONE` — constant (foreign: crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/limb.rs:72 (crate source):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/limb.rs.html#72

    The constant `Limb(1)`. Aeneas models Rust constants as monadic values, hence the
    `Result` type.

    Used by `invert`'s `step` (initial negation carry `Limb::ONE & should_negate` and the
    parity mask `u_sub_v.as_limbs()[0] & Limb::ONE`, src/field/verified/invert.rs) and by
    `from_repr::reduced` (top-bit mask `Limb::ONE << (Limb::BITS - 1)`,
    src/field/verified/mod.rs:151).

    Model: `ok 1#u64`.

    Aeneas metadata:
    [crypto_bigint::limb::{crypto_bigint::limb::Limb}::ONE]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/limb.rs', lines 72:4-72:23 -/
@[rust_const "crypto_bigint::limb::{crypto_bigint::limb::Limb}::ONE"]
def crypto_bigint.limb.Limb.ONE : Result crypto_bigint.limb.Limb :=
  ok 1#u64

/-- **Rust:** `crypto_bigint::Limb::MAX` — constant (foreign: crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/limb.rs:75 (crate source):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/limb.rs.html#75

    The constant `Limb(Word::MAX)` = 2^64 - 1, the all-ones limb.

    Used by `red256` to clear the top bit of the highest limb via the mask `Limb::MAX >> 1`
    = 2^63 - 1 (src/field/verified/red.rs:11), isolating the value below 2^255 before adding
    back `high_bit * (2^255 - p)`.

    Model: the all-ones limb; `ok ⟨BitVec.allOnes 64⟩`.

    Aeneas metadata:
    [crypto_bigint::limb::{crypto_bigint::limb::Limb}::MAX]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/limb.rs', lines 75:4-75:23 -/
@[rust_const "crypto_bigint::limb::{crypto_bigint::limb::Limb}::MAX"]
def crypto_bigint.limb.Limb.MAX : Result crypto_bigint.limb.Limb :=
  ok HelioseleneModel.limbAllOnes

/-- **Rust:** `crypto_bigint::Limb::BITS` — constant (foreign: crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/limb.rs:90 (64-bit definition):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/limb.rs.html#90

    Bit width of a limb: 64. The crate also has a 32-bit definition (`BITS = 32`, line 81)
    selected by `target_pointer_width`; the extraction used the 64-bit branch, so the 64-bit
    target assumption is baked into this definition (and into `Limb := Std.U64` in Types.lean).

    Used for shift amounts (`Limb::BITS - 1` = 63) in `red256`, `invert`'s `step` and
    `from_repr::reduced`, and for the iteration counts `2 * Limb::BITS` of `invert`'s outer
    loops.

    Model: `ok 64#usize`.

    Aeneas metadata:
    [crypto_bigint::limb::{crypto_bigint::limb::Limb}::BITS]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/limb.rs', lines 90:4-90:25 -/
@[rust_const "crypto_bigint::limb::{crypto_bigint::limb::Limb}::BITS"]
def crypto_bigint.limb.Limb.BITS : Result Std.Usize :=
  ok 64#usize

/-- **Rust:** `crypto_bigint::Uint::<LIMBS>::wrapping_add` — function (foreign:
    crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/uint/add.rs:31-33 (crate source; carry chain `adc` at 10-22):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/uint/add.rs.html#31-33

    Multi-limb addition mod 2^(64*LIMBS): runs the limb-wise add-with-carry chain (`adc`) and
    discards the final carry-out.

    Used by field addition (`impl Add for HelioseleneField`: `self.0.wrapping_add(&b.0)`
    followed by `red1`, src/field/verified/mod.rs:72), where inputs below p < 2^255 make
    wrapping impossible, and by field subtraction's correction
    `candidate.wrapping_add(&MODULUS)` (src/field/verified/mod.rs:81), where wrap-around is
    intentional: adding p to an underflowed (wrapped) difference wraps back to the in-range
    result.

    Model: `ok (ofNat LIMBS (a.toNat + b.toNat))` — (a + b) mod 2^(64·LIMBS).

    Aeneas metadata:
    [crypto_bigint::uint::add::{crypto_bigint::uint::Uint<LIMBS>}::wrapping_add]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/uint/add.rs', lines 31:4-31:56 -/
@[rust_fun
  "crypto_bigint::uint::add::{crypto_bigint::uint::Uint<@LIMBS>}::wrapping_add"]
def crypto_bigint.uint.add.Uint.wrapping_add
  {LIMBS : Std.Usize} :
  crypto_bigint.uint.Uint LIMBS → crypto_bigint.uint.Uint LIMBS → Result
    (crypto_bigint.uint.Uint LIMBS) :=
  fun a b => ok (crypto_bigint.uint.Uint.ofNat LIMBS (a.toNat + b.toNat))

/-- **Rust:** `crypto_bigint::Uint::<LIMBS>::from_be_hex` — function (foreign:
    crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/uint/encoding.rs:38-67 (crate source):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/uint/encoding.rs.html#38-67

    Const-fn parser: converts a big-endian hex string of exactly `Limb::BYTES * LIMBS * 2`
    characters into a `Uint`, panicking on a wrong length or non-hex characters (all call
    sites here pass valid literals of the right length).

    Used to define the compile-time constants of the field: `MODULUS` p
    (src/field/mod.rs:25-26), `MODULUS_255_DISTANCE` = 2^255 - p (src/field/verified/mod.rs:26),
    `TWO_MODULUS_255_DISTANCE` = 2^256 - 2p (src/field/verified/red.rs:4), and `invert`'s
    `MODULUS_XOR_TWO_MODULUS` (src/field/verified/invert.rs:127-128).

    Model: real big-endian hex parser — `ok (ofNat LIMBS value)` when the byte string has
    length 16·LIMBS and all bytes are hex digits, `fail panic` otherwise.

    Aeneas metadata:
    [crypto_bigint::uint::encoding::{crypto_bigint::uint::Uint<LIMBS>}::from_be_hex]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/uint/encoding.rs', lines 38:4-38:47 -/
@[rust_fun
  "crypto_bigint::uint::encoding::{crypto_bigint::uint::Uint<@LIMBS>}::from_be_hex"]
def crypto_bigint.uint.encoding.Uint.from_be_hex
  (LIMBS : Std.Usize) : Str → Result (crypto_bigint.uint.Uint LIMBS) :=
  fun s =>
    if s.val.length = 16 * LIMBS.val then
      match HelioseleneModel.parseBeHex? s.val with
      | some n => ok (crypto_bigint.uint.Uint.ofNat LIMBS n)
      | none => fail Error.panic
    else fail Error.panic

/-- **Rust:** `crypto_bigint::Uint::<LIMBS>::from_le_slice` — function (foreign:
    crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/uint/encoding.rs:70-91 (crate source):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/uint/encoding.rs.html#70-91

    Const-fn constructor: interprets a little-endian byte slice of exactly
    `Limb::BYTES * LIMBS` bytes as a `Uint` (8 bytes per limb, least-significant limb first),
    panicking on any other length.

    Used by `from_repr` to deserialize a candidate 32-byte field-element encoding into a U256
    before checking that it is fully reduced (src/field/verified/mod.rs:139).

    Model: `ok (ofNat LIMBS (little-endian value of the bytes))` when the slice has length
    8·LIMBS, `fail panic` otherwise.

    Aeneas metadata:
    [crypto_bigint::uint::encoding::{crypto_bigint::uint::Uint<LIMBS>}::from_le_slice]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/uint/encoding.rs', lines 70:4-70:52 -/
@[rust_fun
  "crypto_bigint::uint::encoding::{crypto_bigint::uint::Uint<@LIMBS>}::from_le_slice"]
def crypto_bigint.uint.encoding.Uint.from_le_slice
  (LIMBS : Std.Usize) : Slice Std.U8 → Result (crypto_bigint.uint.Uint LIMBS) :=
  fun s =>
    if s.val.length = 8 * LIMBS.val then
      ok (crypto_bigint.uint.Uint.ofNat LIMBS (HelioseleneModel.leBytesToNat s.val))
    else fail Error.panic

/-- **Rust:** `<crypto_bigint::U256 as crypto_bigint::Encoding>::to_le_bytes` — trait-impl
    method (foreign: crypto-bigint 0.5.5, macro-generated)
    crypto-bigint 0.5.5, src/uint/macros.rs:31-36 (instantiated for `U256` = `Uint<4>` at
    src/uint.rs:305, inside the `impl_uint_aliases!` invocation beginning at line 301):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/uint/macros.rs.html#31-36

    Serializes a 256-bit integer to its canonical 32-byte little-endian representation
    (each 64-bit limb written in little-endian order, least-significant limb first). The impl
    is generated by the `impl_uint_aliases!` macro, which is why the Aeneas source span points
    into macros.rs.

    Used by `to_repr`, the canonical serialization of a field element
    (src/field/verified/mod.rs:159-161).

    Model: byte i of the result is bits [8·i, 8·i+8) of the value — the 32 little-endian
    bytes, as an `Array U8 32`.

    Aeneas metadata:
    [crypto_bigint::uint::{impl crypto_bigint::traits::Encoding<[u8; 32usize]> for crypto_bigint::uint::Uint<4usize>}::to_le_bytes]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/uint/macros.rs', lines 31:16-31:51 -/
@[rust_fun
  "crypto_bigint::uint::{crypto_bigint::traits::Encoding<crypto_bigint::uint::Uint<4>, [u8; 32]>}::to_le_bytes"]
def
  crypto_bigint.uint.Uint4.Insts.Crypto_bigintTraitsEncodingArrayU832.to_le_bytes
  : crypto_bigint.uint.Uint 4#usize → Result (Array Std.U8 32#usize) :=
  fun u =>
    ok (Array.make 32#usize
      (List.ofFn (fun (i : Fin 32) => HelioseleneModel.byteOfNat (u.toNat >>> (8 * i.val)))))

/-- **Rust:** `crypto_bigint::Uint::<LIMBS>::mul_wide` — function (foreign: crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/uint/mul.rs:31-67 (crate source):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/uint/mul.rs.html#31-67

    Schoolbook multiplication of a LIMBS-limb by an HLIMBS-limb integer using `Limb::mac`,
    returning the exact double-width product as the pair (lo, hi) — low half first (the
    ordering changed in crypto-bigint 0.3). Constant-time: the full multiplication grid is
    always computed.

    Used by field multiplication: `red512(self.0.mul_wide(&b.0))`
    (src/field/verified/mod.rs:110-114); this is what the `*` operator on field elements
    (`Mul::mul`) evaluates.

    Model: p := a.toNat · b.toNat, split at 2^(64·LIMBS): `ok (ofNat LIMBS p,
    ofNat HLIMBS (p >>> 64·LIMBS))`.

    Aeneas metadata:
    [crypto_bigint::uint::mul::{crypto_bigint::uint::Uint<LIMBS>}::mul_wide]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/uint/mul.rs', lines 31:4-31:97 -/
@[rust_fun
  "crypto_bigint::uint::mul::{crypto_bigint::uint::Uint<@LIMBS>}::mul_wide"]
def crypto_bigint.uint.mul.Uint.mul_wide
  {LIMBS : Std.Usize} {HLIMBS : Std.Usize} :
  crypto_bigint.uint.Uint LIMBS → crypto_bigint.uint.Uint HLIMBS → Result
    ((crypto_bigint.uint.Uint LIMBS) × (crypto_bigint.uint.Uint HLIMBS)) :=
  fun a b =>
    let p := a.toNat * b.toNat
    ok (crypto_bigint.uint.Uint.ofNat LIMBS p,
        crypto_bigint.uint.Uint.ofNat HLIMBS (p >>> (64 * LIMBS.val)))

/-- **Rust:** `crypto_bigint::Uint::<LIMBS>::square_wide` — function (foreign:
    crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/uint/mul.rs:90-161 (crate source):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/uint/mul.rs.html#90-161

    Squaring returning the exact double-width result as (lo, hi). Computes only the strict
    upper half of the schoolbook multiplication grid, doubles it by shifting, then adds the
    diagonal terms `limb[i]^2` — roughly half the limb multiplications of a general
    `mul_wide`.

    Used by field squaring: `red512(value.0.square_wide())` (src/field/verified/mod.rs:118-120).

    Model: p := a.toNat², split at 2^(64·LIMBS): `ok (ofNat LIMBS p,
    ofNat LIMBS (p >>> 64·LIMBS))`.

    Aeneas metadata:
    [crypto_bigint::uint::mul::{crypto_bigint::uint::Uint<LIMBS>}::square_wide]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/uint/mul.rs', lines 90:4-90:51 -/
@[rust_fun
  "crypto_bigint::uint::mul::{crypto_bigint::uint::Uint<@LIMBS>}::square_wide"]
def crypto_bigint.uint.mul.Uint.square_wide
  {LIMBS : Std.Usize} :
  crypto_bigint.uint.Uint LIMBS → Result ((crypto_bigint.uint.Uint LIMBS) ×
    (crypto_bigint.uint.Uint LIMBS)) :=
  fun a =>
    let p := a.toNat * a.toNat
    ok (crypto_bigint.uint.Uint.ofNat LIMBS p,
        crypto_bigint.uint.Uint.ofNat LIMBS (p >>> (64 * LIMBS.val)))

/-- **Rust:** `crypto_bigint::Uint::<LIMBS>::shl_vartime` — function (foreign:
    crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/uint/shl.rs:42-60 (crate source):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/uint/shl.rs.html#42-60

    Left shift by `n` bits, returning zero if `n` >= 64*LIMBS. Variable-time with respect to
    the shift amount only — constant-time in the value being shifted, so it is safe on secrets
    when `n` is a public constant.

    Used by field doubling: `red1(value.0.shl_vartime(1))` (src/field/verified/mod.rs:104-107).
    The shift amount is the constant 1, so no secret-dependent timing arises.

    Model: `ok (ofNat LIMBS (a.toNat <<< s.val))` when s.val < 64·LIMBS, `fail panic`
    otherwise (conservative; all call sites shift by 1).

    Aeneas metadata:
    [crypto_bigint::uint::shl::{crypto_bigint::uint::Uint<LIMBS>}::shl_vartime]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/uint/shl.rs', lines 42:4-42:53 -/
@[rust_fun
  "crypto_bigint::uint::shl::{crypto_bigint::uint::Uint<@LIMBS>}::shl_vartime"]
def crypto_bigint.uint.shl.Uint.shl_vartime
  {LIMBS : Std.Usize} :
  crypto_bigint.uint.Uint LIMBS → Std.Usize → Result
    (crypto_bigint.uint.Uint LIMBS) :=
  fun a s =>
    if s.val < 64 * LIMBS.val then
      ok (crypto_bigint.uint.Uint.ofNat LIMBS (a.toNat <<< s.val))
    else fail Error.panic

/-- **Rust:** `crypto_bigint::Uint::<LIMBS>::shr_vartime` — function (foreign:
    crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/uint/shr.rs:48-79 (crate source):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/uint/shr.rs.html#48-79

    Right shift by `shift` bits, returning zero if the shift exceeds 64*LIMBS. Variable-time
    with respect to the shift amount only — constant-time in the value being shifted.

    Used by `invert`'s `step` to halve `a` and `u` at the end of every binary-GCD iteration
    (`*a = a.shr_vartime(1); *u = u.shr_vartime(1);`, src/field/verified/invert.rs:171-172).
    The shift amount is the constant 1, so no secret-dependent timing arises.

    Model: `ok (ofNat LIMBS (a.toNat >>> s.val))` when s.val < 64·LIMBS, `fail panic`
    otherwise (conservative; all call sites shift by 1).

    Aeneas metadata:
    [crypto_bigint::uint::shr::{crypto_bigint::uint::Uint<LIMBS>}::shr_vartime]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/uint/shr.rs', lines 48:4-48:57 -/
@[rust_fun
  "crypto_bigint::uint::shr::{crypto_bigint::uint::Uint<@LIMBS>}::shr_vartime"]
def crypto_bigint.uint.shr.Uint.shr_vartime
  {LIMBS : Std.Usize} :
  crypto_bigint.uint.Uint LIMBS → Std.Usize → Result
    (crypto_bigint.uint.Uint LIMBS) :=
  fun a s =>
    if s.val < 64 * LIMBS.val then
      ok (crypto_bigint.uint.Uint.ofNat LIMBS (a.toNat >>> s.val))
    else fail Error.panic

/-- **Rust:** `crypto_bigint::Uint::<LIMBS>::sbb` — function (foreign: crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/uint/sub.rs:11-23 (crate source):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/uint/sub.rs.html#11-23

    Multi-limb subtract-with-borrow: computes `self - (rhs + borrow)` with a limb-wise borrow
    chain and returns (difference, final borrow). The final borrow is `Limb::ZERO` when no
    underflow occurred and `Limb::MAX` (an all-ones mask) on underflow, directly usable for
    constant-time selection.

    Used via the helper `sub_value` (src/field/verified/mod.rs:50-55), which underlies field
    subtraction (`a - b`, adding p back when the raw difference underflows) and `red1`
    (subtract p once, keep the original on underflow).

    Model: borrow-in is the TOP bit of the borrow limb (borrow.val >>> 63, matching the Rust
    borrow chain); `ok ((a - b - borrow_in) mod 2^(64·LIMBS), borrow-out)` with borrow-out =
    all-ones on underflow, 0 otherwise.

    Aeneas metadata:
    [crypto_bigint::uint::sub::{crypto_bigint::uint::Uint<LIMBS>}::sbb]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/uint/sub.rs', lines 11:4-11:73 -/
@[rust_fun
  "crypto_bigint::uint::sub::{crypto_bigint::uint::Uint<@LIMBS>}::sbb"]
def crypto_bigint.uint.sub.Uint.sbb
  {LIMBS : Std.Usize} :
  crypto_bigint.uint.Uint LIMBS → crypto_bigint.uint.Uint LIMBS →
    crypto_bigint.limb.Limb → Result ((crypto_bigint.uint.Uint LIMBS) ×
    crypto_bigint.limb.Limb) :=
  fun a b borrow =>
    let borrowIn := borrow.val >>> 63
    let diff :=
      crypto_bigint.uint.Uint.ofNat LIMBS
        (a.toNat + 2 ^ (64 * LIMBS.val) - (b.toNat + borrowIn))
    let borrowOut : Std.U64 :=
      if a.toNat < b.toNat + borrowIn then HelioseleneModel.limbAllOnes else 0#u64
    ok (diff, borrowOut)

/-- **Rust:** `crypto_bigint::Uint::<LIMBS>::wrapping_sub` — function (foreign:
    crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/uint/sub.rs:33-35 (crate source):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/uint/sub.rs.html#33-35

    Multi-limb subtraction mod 2^(64*LIMBS): runs `sbb` with a zero initial borrow and
    discards the final borrow.

    Used by field negation (`impl Neg for HelioseleneField`): `MODULUS.wrapping_sub(&self.0)`
    computes p - a (src/field/verified/mod.rs:93-101), which is then constant-time-selected
    against 0 for the a = 0 case; this is what the unary `-` operator (`Neg::neg`) evaluates.

    Model: `ok (ofNat LIMBS (a.toNat + 2^(64·LIMBS) - b.toNat))` — (a - b) mod 2^(64·LIMBS).

    Aeneas metadata:
    [crypto_bigint::uint::sub::{crypto_bigint::uint::Uint<LIMBS>}::wrapping_sub]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/uint/sub.rs', lines 33:4-33:56 -/
@[rust_fun
  "crypto_bigint::uint::sub::{crypto_bigint::uint::Uint<@LIMBS>}::wrapping_sub"]
def crypto_bigint.uint.sub.Uint.wrapping_sub
  {LIMBS : Std.Usize} :
  crypto_bigint.uint.Uint LIMBS → crypto_bigint.uint.Uint LIMBS → Result
    (crypto_bigint.uint.Uint LIMBS) :=
  fun a b =>
    ok (crypto_bigint.uint.Uint.ofNat LIMBS (a.toNat + 2 ^ (64 * LIMBS.val) - b.toNat))

/-- **Rust:** `crypto_bigint::Uint::<LIMBS>::ZERO` — constant (foreign: crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/uint.rs:80 (crate source):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/uint.rs.html#80

    The constant 0 (all limbs zero). Aeneas models Rust constants as monadic values and passes
    the limb count explicitly, hence the `(LIMBS : Std.Usize) : Result (Uint LIMBS)` shape.

    Used as the field's `ff::Field::ZERO` and as the initial accumulator in `red1`, `red512`,
    `invert` (`v = U256::ZERO`) and `invert`'s `step`/`select` helpers.

    Model: `ok (ofNat LIMBS 0)`.

    Aeneas metadata:
    [crypto_bigint::uint::{crypto_bigint::uint::Uint<LIMBS>}::ZERO]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/uint.rs', lines 80:4-80:24 -/
@[rust_const "crypto_bigint::uint::{crypto_bigint::uint::Uint<@LIMBS>}::ZERO"]
def crypto_bigint.uint.Uint.ZERO (LIMBS : Std.Usize)
  : Result (crypto_bigint.uint.Uint LIMBS) :=
  ok (crypto_bigint.uint.Uint.ofNat LIMBS 0)

/-- **Rust:** `crypto_bigint::Uint::<LIMBS>::ONE` — constant (foreign: crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/uint.rs:83 (crate source):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/uint.rs.html#83

    The constant 1 (limb 0 set to one, all others zero).

    Used by `invert` to initialize the Bezout-coefficient accumulator `u = U256::ONE` of the
    constant-time binary GCD (Algorithm 1 of https://eprint.iacr.org/2020/972;
    src/field/verified/invert.rs:26).

    Model: `ok (ofNat LIMBS 1)`.

    Aeneas metadata:
    [crypto_bigint::uint::{crypto_bigint::uint::Uint<LIMBS>}::ONE]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/uint.rs', lines 83:4-83:23 -/
@[rust_const "crypto_bigint::uint::{crypto_bigint::uint::Uint<@LIMBS>}::ONE"]
def crypto_bigint.uint.Uint.ONE (LIMBS : Std.Usize)
  : Result (crypto_bigint.uint.Uint LIMBS) :=
  ok (crypto_bigint.uint.Uint.ofNat LIMBS 1)

/-- **Rust:** `crypto_bigint::Uint::<LIMBS>::LIMBS` — constant (foreign: crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/uint.rs:101 (crate source):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/uint.rs.html#101

    The associated constant `pub const LIMBS: usize = LIMBS`: the number of limbs, i.e. the
    const-generic parameter re-exported as a value (4 for U256, 2 for U128). Aeneas appends
    `#1` (Lean: `_1`) to distinguish the associated constant from the const-generic parameter
    of the same name.

    Used pervasively as the bound of `for j in 0 .. U256::LIMBS`-style loops throughout the
    translated field code (`is_zero`, `red1`, `red256`, `red512`, `invert`,
    `from_repr::reduced`).

    Model: `ok LIMBS` — the const-generic parameter itself.

    Aeneas metadata:
    [crypto_bigint::uint::{crypto_bigint::uint::Uint<LIMBS>}::LIMBS#1]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/uint.rs', lines 101:4-101:26 -/
@[rust_const
  "crypto_bigint::uint::{crypto_bigint::uint::Uint<@LIMBS>}::LIMBS#1"]
def crypto_bigint.uint.Uint.LIMBS_1 (LIMBS : Std.Usize) : Result Std.Usize :=
  ok LIMBS

/-- **Rust:** `crypto_bigint::Uint::<LIMBS>::as_limbs` — function (foreign: crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/uint.rs:157-159 (crate source):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/uint.rs.html#157-159

    Borrows the internal limb array as `&[Limb; LIMBS]` (little-endian limb order: index 0 is
    least significant). Aeneas translates the shared borrow simply as returning the array
    value.

    Used everywhere limbs are read in the translated field code: `is_zero`, `is_odd`, `red1`,
    `red256`, `red512`, `invert` and its `step`, and `from_repr::reduced`.

    Model: the identity (a `Uint` IS its limb array under this instantiation); `ok u`.

    Aeneas metadata:
    [crypto_bigint::uint::{crypto_bigint::uint::Uint<LIMBS>}::as_limbs]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/uint.rs', lines 157:4-157:50 -/
@[rust_fun
  "crypto_bigint::uint::{crypto_bigint::uint::Uint<@LIMBS>}::as_limbs"]
def crypto_bigint.uint.Uint.as_limbs
  {LIMBS : Std.Usize} :
  crypto_bigint.uint.Uint LIMBS → Result (Array crypto_bigint.limb.Limb
    LIMBS) :=
  fun u => ok u

/-- **Rust:** `crypto_bigint::Uint::<LIMBS>::as_limbs_mut` — function (foreign:
    crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/uint.rs:162-164 (crate source):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/uint.rs.html#162-164

    Mutably borrows the internal limb array as `&mut [Limb; LIMBS]`. Aeneas translates the
    mutable borrow as a pair: the current limb array plus a backward function
    `Array Limb LIMBS → Uint LIMBS` that rebuilds the integer from an updated array. A Rust
    write `x.as_limbs_mut()[j] = w` therefore becomes: get the array, update index j, apply
    the backward function.

    Model: `ok (u, fun a => a)` — the array is the `Uint` itself and the backward function is
    the identity.

    Aeneas metadata:
    [crypto_bigint::uint::{crypto_bigint::uint::Uint<LIMBS>}::as_limbs_mut]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/uint.rs', lines 162:4-162:56 -/
@[rust_fun
  "crypto_bigint::uint::{crypto_bigint::uint::Uint<@LIMBS>}::as_limbs_mut"]
def crypto_bigint.uint.Uint.as_limbs_mut
  {LIMBS : Std.Usize} :
  crypto_bigint.uint.Uint LIMBS → Result ((Array crypto_bigint.limb.Limb
    LIMBS) × (Array crypto_bigint.limb.Limb LIMBS → crypto_bigint.uint.Uint
    LIMBS)) :=
  fun u => ok (u, fun a => a)

/-- **Rust:** `<crypto_bigint::Uint<LIMBS> as subtle::ConditionallySelectable>::
    conditional_select` — trait-impl method (foreign: crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/uint.rs:197-205 (crate source):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/uint.rs.html#197-205

    Constant-time selection between two Uints: returns `a` when `choice` is 0 and `b` when
    `choice` is 1, picking every limb with mask arithmetic (`Limb::conditional_select`) —
    no data-dependent branch or memory access.

    Backs `impl ConditionallySelectable for HelioseleneField` (src/field/mod.rs:60-62), which
    field negation uses to output 0 instead of p when the input is 0
    (src/field/verified/mod.rs:93-101).

    Model: `ok (if c then b else a)` — choice 1 (true) selects b, per subtle's convention.

    Aeneas metadata:
    [crypto_bigint::uint::{impl subtle::ConditionallySelectable for crypto_bigint::uint::Uint<LIMBS>}::conditional_select]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/uint.rs', lines 197:4-197:69 -/
@[rust_fun
  "crypto_bigint::uint::{subtle::ConditionallySelectable<crypto_bigint::uint::Uint<@LIMBS>>}::conditional_select"]
def
  crypto_bigint.uint.Uint.Insts.SubtleConditionallySelectable.conditional_select
  {LIMBS : Std.Usize} :
  crypto_bigint.uint.Uint LIMBS → crypto_bigint.uint.Uint LIMBS →
    subtle.Choice → Result (crypto_bigint.uint.Uint LIMBS) :=
  fun a b c => ok (if c then b else a)

/-- **Rust:** `<subtle::Choice as core::ops::Not>::not` — trait-impl method (foreign:
    subtle 2.6.1)
    subtle 2.6.1, src/lib.rs:204-210 (method at line 207):
    https://docs.rs/subtle/2.6.1/src/subtle/lib.rs.html#204-210

    Logical negation of a constant-time boolean: computes `(1u8 & !self.0).into()`, mapping
    1 to 0 and 0 to 1 with pure bit arithmetic (no branch) and re-wrapping through `Choice`'s
    optimization barrier.

    Used by `invert`: the returned `CtOption` is flagged valid with `!value.is_zero()`
    (src/field/verified/invert.rs:194) — zero has no multiplicative inverse.

    Model: boolean negation; `ok (!c)` (Choice = Bool).

    Aeneas metadata:
    [subtle::{impl core::ops::bit::Not<subtle::Choice> for subtle::Choice}::not]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/subtle-2.6.1/src/lib.rs', lines 207:4-207:26 -/
@[rust_fun
  "subtle::{core::ops::bit::Not<subtle::Choice, subtle::Choice>}::not"]
def subtle.Choice.Insts.CoreOpsBitNotChoice.not
  : subtle.Choice → Result subtle.Choice :=
  fun c => ok (!c)

/-- **Rust:** `<subtle::Choice as core::convert::From<u8>>::from` — trait-impl method
    (foreign: subtle 2.6.1)
    subtle 2.6.1, src/lib.rs:236-245 (method at line 238):
    https://docs.rs/subtle/2.6.1/src/subtle/lib.rs.html#236-245

    Wraps a `u8` that must be 0 or 1 (debug-asserted) into a `Choice`. The byte is passed
    through `black_box` — a volatile-read optimization barrier — so the compiler cannot infer
    that the wrapped value is really a boolean and reintroduce data-dependent branches.

    Used by `is_odd`: `Choice::from((value.0.as_limbs()[0].0 & 1) as u8)`
    (src/field/verified/mod.rs:132-135).

    Model: `ok (u.val != 0)` — inputs outside {0, 1} are outside subtle's contract; the model
    identifies them with `true`.

    Aeneas metadata:
    [subtle::{impl core::convert::From<u8> for subtle::Choice}::from]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/subtle-2.6.1/src/lib.rs', lines 238:4-238:32 -/
@[rust_fun "subtle::{core::convert::From<subtle::Choice, u8>}::from"]
def subtle.Choice.Insts.CoreConvertFromU8.from
  : Std.U8 → Result subtle.Choice :=
  fun u => ok (u.val != 0)

/-- **Rust:** `subtle::CtOption::<T>::new` — function (foreign: subtle 2.6.1)
    subtle 2.6.1, src/lib.rs:678-683 (crate source):
    https://docs.rs/subtle/2.6.1/src/subtle/lib.rs.html#678-683

    Constructs a `CtOption<T>` from a value and an `is_some` `Choice`. The value is stored
    unconditionally — even when `is_some` is 0 — so constructing the option leaks nothing
    about validity; accessors only expose the value when `is_some` is 1.

    Used by `invert` (the inverse is valid iff the input is nonzero,
    src/field/verified/invert.rs:194) and by `from_repr` (the decoded element is valid iff
    the 32-byte encoding is fully reduced, src/field/verified/mod.rs:138-156).

    Model: the pair constructor; `ok (v, c)` (CtOption T = T × Bool).

    Aeneas metadata:
    [subtle::{subtle::CtOption<T>}::new]:
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/subtle-2.6.1/src/lib.rs', lines 678:4-678:56 -/
@[rust_fun "subtle::{subtle::CtOption<@T>}::new"]
def subtle.CtOption.new
  {T : Type} : T → subtle.Choice → Result (subtle.CtOption T) :=
  fun v c => ok (v, c)

/-! ## Sanity checks -/

section SanityChecks
open crypto_bigint.uint.Uint HelioseleneModel

-- toNat/ofNat round-trip on a 2-limb value straddling the limb boundary
#guard (ofNat 2#usize 0x10000000000000005).toNat == 0x10000000000000005
-- ofNat wraps mod 2^(64·LIMBS)
#guard (ofNat 1#usize (2 ^ 64 + 3)).toNat == 3

-- mac on small numbers: 2 + 3·4 + 5 = 19
#guard match crypto_bigint.limb.mul.Limb.mac 2#u64 3#u64 4#u64 5#u64 with
  | ok (lo, hi) => lo.val == 19 && hi.val == 0
  | _ => false
-- mac at the extreme: (2^64-1) + (2^64-1)² + (2^64-1) = 2^128 - 1 (no overflow)
#guard match crypto_bigint.limb.mul.Limb.mac limbAllOnes limbAllOnes limbAllOnes limbAllOnes with
  | ok (lo, hi) => lo.val == 2 ^ 64 - 1 && hi.val == 2 ^ 64 - 1
  | _ => false

-- sbb borrow conventions on 1-limb values: 5 - 7 underflows, borrow-out = all-ones
#guard match crypto_bigint.uint.sub.Uint.sbb (ofNat 1#usize 5) (ofNat 1#usize 7) 0#u64 with
  | ok (d, bo) => d.toNat == 2 ^ 64 - 2 && bo.val == 2 ^ 64 - 1
  | _ => false
-- borrow-in is read from the TOP bit of the borrow limb: 7 - 5 - 1 = 1, no borrow-out
#guard match crypto_bigint.uint.sub.Uint.sbb (ofNat 1#usize 7) (ofNat 1#usize 5) limbAllOnes with
  | ok (d, bo) => d.toNat == 1 && bo.val == 0
  | _ => false

-- from_be_hex parses a 1-limb literal
#guard match crypto_bigint.uint.encoding.Uint.from_be_hex 1#usize (toStr "00000000000000fF") with
  | ok u => u.toNat == 0xff
  | _ => false
-- from_be_hex panics on a wrong-length string
#guard match crypto_bigint.uint.encoding.Uint.from_be_hex 1#usize (toStr "ff") with
  | .ok _ => false
  | _ => true

-- limb shifts panic at width 64, work below it
#guard match crypto_bigint.limb.Limb.Insts.CoreOpsBitShlUsizeLimb.shl 1#u64 63#usize with
  | ok l => l.val == 2 ^ 63
  | _ => false
#guard match crypto_bigint.limb.Limb.Insts.CoreOpsBitShlUsizeLimb.shl 1#u64 64#usize with
  | .fail _ => true
  | _ => false

-- Choice::from maps 0 to false and nonzero to true
#guard subtle.Choice.Insts.CoreConvertFromU8.from 0#u8 == ok false
#guard subtle.Choice.Insts.CoreConvertFromU8.from 1#u8 == ok true

end SanityChecks
