-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [helioselene]: type definitions
import Aeneas
import HelioseleneCore.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace helioselene

/-- **Rust:** `core::ops::Add` — trait declaration (foreign: Rust core library)
    core/src/ops/arith.rs (trait `Add<Rhs = Self>` with associated type `Output`):
    https://doc.rust-lang.org/core/ops/trait.Add.html

    Aeneas encodes a Rust trait as a Lean structure with one field per method: a trait impl
    becomes a record value of this type, and trait-generic code takes the record as an
    argument (dictionary passing). Here `add : Self → Rhs → Result Self_Output` is the method
    behind the binary `+` operator — `a + b` elaborates to `Add::add(a, b)` — and the
    associated `Output` type is flattened into the extra type parameter `Self_Output`.

    Instantiated in this development by `impl Add for HelioseleneField`
    (src/field/verified/mod.rs):
    field addition a + b mod p (wrapping_add then a single conditional reduction red1).

    Aeneas metadata:
    Trait declaration: [core::ops::arith::Add]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 76:0-76:31 -/
@[rust_trait "core::ops::arith::Add"]
structure core.ops.arith.Add (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  add : Self → Rhs → Result Self_Output

/-- **Rust:** `core::ops::Sub` — trait declaration (foreign: Rust core library)
    core/src/ops/arith.rs (trait `Sub<Rhs = Self>` with associated type `Output`):
    https://doc.rust-lang.org/core/ops/trait.Sub.html

    Aeneas encodes a Rust trait as a Lean structure with one field per method: a trait impl
    becomes a record value of this type, and trait-generic code takes the record as an
    argument (dictionary passing). Here `sub : Self → Rhs → Result Self_Output` is the method
    behind the binary `-` operator — `a - b` elaborates to `Sub::sub(a, b)` — and the
    associated `Output` type is flattened into the extra type parameter `Self_Output`.

    Instantiated in this development by `impl Sub for HelioseleneField`
    (src/field/verified/mod.rs):
    field subtraction a - b mod p (borrow-based subtract, adding p back on underflow).

    Aeneas metadata:
    Trait declaration: [core::ops::arith::Sub]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 188:0-188:31 -/
@[rust_trait "core::ops::arith::Sub"]
structure core.ops.arith.Sub (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  sub : Self → Rhs → Result Self_Output

/-- **Rust:** `core::ops::Mul` — trait declaration (foreign: Rust core library)
    core/src/ops/arith.rs (trait `Mul<Rhs = Self>` with associated type `Output`):
    https://doc.rust-lang.org/core/ops/trait.Mul.html

    Aeneas encodes a Rust trait as a Lean structure with one field per method: a trait impl
    becomes a record value of this type, and trait-generic code takes the record as an
    argument (dictionary passing). Here `mul : Self → Rhs → Result Self_Output` is the method
    behind the binary `*` operator — `a * b` elaborates to `Mul::mul(a, b)` — and the
    associated `Output` type is flattened into the extra type parameter `Self_Output`.

    Instantiated in this development by `impl Mul for HelioseleneField`
    (src/field/verified/mod.rs):
    field multiplication a * b mod p (mul_wide then the red512 Crandall reduction).

    Aeneas metadata:
    Trait declaration: [core::ops::arith::Mul]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 322:0-322:31 -/
@[rust_trait "core::ops::arith::Mul"]
structure core.ops.arith.Mul (Self : Type) (Rhs : Type) (Self_Output : Type)
  where
  mul : Self → Rhs → Result Self_Output

/-- **Rust:** `core::ops::Neg` — trait declaration (foreign: Rust core library)
    core/src/ops/arith.rs (trait `Neg` with associated type `Output`):
    https://doc.rust-lang.org/core/ops/trait.Neg.html

    Aeneas encodes a Rust trait as a Lean structure with one field per method: a trait impl
    becomes a record value of this type. Here `neg : Self → Result Self_Output` is the method
    behind the unary `-` operator — `-a` elaborates to `Neg::neg(a)` — and the associated
    `Output` type is flattened into the extra type parameter `Self_Output`.

    Instantiated in this development by `impl Neg for HelioseleneField`
    (src/field/verified/mod.rs): field negation, computing p - a with `wrapping_sub` and
    constant-time-selecting 0 when a = 0.

    Aeneas metadata:
    Trait declaration: [core::ops::arith::Neg]
    Source: '/rustc/library/core/src/ops/arith.rs', lines 690:0-690:19 -/
@[rust_trait "core::ops::arith::Neg"]
structure core.ops.arith.Neg (Self : Type) (Self_Output : Type) where
  neg : Self → Result Self_Output

/-- **Rust:** `crypto_bigint::Limb` — type (foreign: crypto-bigint 0.5.5, newtype flattened)
    crypto-bigint 0.5.5, src/limb.rs:65 (crate source):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/limb.rs.html#65

    Rust defines `pub struct Limb(pub Word)` — a `#[repr(transparent)]` newtype over the
    CPU-word type `Word`, which is `u64` on 64-bit targets and `u32` on 32-bit ones
    (src/limb.rs:38/50). Aeneas flattens the newtype away, so a limb is simply `Std.U64` here.
    This bakes the 64-bit-target assumption into the whole translation: the Lean development
    is only faithful to helioselene as compiled for 64-bit platforms.

    A `Uint LIMBS` is an array of these; every mask, carry and multiply-accumulate operation
    in the translated field code manipulates this type.

    Aeneas metadata:
    [crypto_bigint::limb::Limb]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/limb.rs', lines 65:0-65:15 -/
@[reducible, rust_type "crypto_bigint::limb::Limb"]
def crypto_bigint.limb.Limb := Std.U64

/-- **Rust:** `helioselene::field::HelioseleneField` — type (newtype flattened)
    crypto/helioselene/src/field/mod.rs:22 in this repository:
    https://github.com/monero-oxide/monero-oxide/blob/6313959f906fe754909754ac642134237dae42a9/crypto/helioselene/src/field/mod.rs#L22

    Rust defines `pub struct HelioseleneField(pub(crate) U256)`, a `#[repr(transparent)]`
    newtype over crypto-bigint's `U256`. Aeneas erases the wrapper, so in Lean a field element
    is a plain `crypto_bigint.uint.Uint 4#usize` — four 64-bit limbs, little-endian. Elements
    represent residues modulo the prime p = 2^255 - 0x8cab7e2e6960ce8067af49720ee20ad, the
    field novel to the Helios/Selene curve cycle; the verified arithmetic keeps values fully
    reduced (below p).

    Every field operation in Funs.lean (add, sub, neg, mul, square, double, invert, is_zero,
    is_odd, from_repr, to_repr, and the reductions red1/red256/red512) takes and returns this
    type. Because the wrapper is erased, the invariant "value < p" is not enforced by the
    type; it must be tracked by any proof development.

    Aeneas metadata:
    [helioselene::field::HelioseleneField]
    Source: 'src/field/mod.rs', lines 22:0-22:45 -/
@[reducible]
def field.HelioseleneField := crypto_bigint.uint.Uint 4#usize

end helioselene
