-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [helioselene]: external types.
-- Instantiated from the template: the external types are given concrete computable models.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-- **Rust:** `subtle::Choice` — type (foreign: subtle 2.6.1)
    subtle 2.6.1, src/lib.rs:120 (crate source):
    https://docs.rs/subtle/2.6.1/src/subtle/lib.rs.html#120

    `pub struct Choice(u8)`: a constant-time boolean. The wrapped byte is maintained as 0 or
    1; the AND/OR/XOR/NOT operators on it never short-circuit, and optimization barriers keep
    the compiler from collapsing it back into a branching `bool`. It is the truth value of
    every constant-time comparison in this codebase (`is_zero`, `is_odd`, `ct_eq`,
    `CtOption` validity).

    Model: `Bool`, with `true` ↔ the wrapped byte 1 and `false` ↔ 0. Bytes outside {0, 1}
    are outside subtle's contract (the crate debug-asserts against them); the model
    identifies any nonzero byte with `true`.

    Aeneas metadata:
    [subtle::Choice]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/subtle-2.6.1/src/lib.rs', lines 120:0-120:17 -/
@[reducible, rust_type "subtle::Choice"]
def subtle.Choice : Type := Bool

/-- **Rust:** `crypto_bigint::Uint<const LIMBS: usize>` — type (foreign: crypto-bigint 0.5.5)
    crypto-bigint 0.5.5, src/uint.rs:73-76 (crate source):
    https://docs.rs/crypto-bigint/0.5.5/src/crypto_bigint/uint.rs.html#73-76

    `pub struct Uint<const LIMBS: usize> { limbs: [Limb; LIMBS] }`: a stack-allocated big
    unsigned integer stored as a little-endian array of 64-bit limbs (limbs[0] least
    significant). The Rust const-generic parameter becomes the explicit `LIMBS : Std.Usize`
    index of this Lean type family. The translation instantiates it at `Uint 4` (Rust `U256`,
    the representation of field elements) and `Uint 2` (`U128`, holding the sub-128-bit
    reduction constants 2^255 - p and 2^256 - 2p).

    Model: `Aeneas.Std.Array Aeneas.Std.U64 LIMBS` — a `LIMBS`-element vector of 64-bit
    limbs in little-endian limb order, exactly matching Rust's `as_limbs` layout.

    Aeneas metadata:
    [crypto_bigint::uint::Uint]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/crypto-bigint-0.5.5/src/uint.rs', lines 73:0-73:35 -/
@[reducible, rust_type "crypto_bigint::uint::Uint"]
def crypto_bigint.uint.Uint (LIMBS : Std.Usize) : Type :=
  Aeneas.Std.Array Aeneas.Std.U64 LIMBS

/-- **Rust:** `subtle::CtOption<T>` — type (foreign: subtle 2.6.1)
    subtle 2.6.1, src/lib.rs:647-650 (crate source):
    https://docs.rs/subtle/2.6.1/src/subtle/lib.rs.html#647-650

    `pub struct CtOption<T> { value: T, is_some: Choice }`: a constant-time `Option`. A value
    of type T is always physically present; whether it is meaningful is recorded in the
    `is_some` `Choice`, so fallible operations can be computed and combined without branching
    on validity. In this development it is the return type of field inversion (`invert`; no
    inverse of 0) and of decoding (`from_repr`; non-canonical encodings are rejected).

    Model: `T × Bool` — the pair (value, is_some flag); the value is retained even when the
    flag is `false`, matching subtle's representation.

    Aeneas metadata:
    [subtle::CtOption]
    Source: '/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/subtle-2.6.1/src/lib.rs', lines 647:0-647:22 -/
@[reducible, rust_type "subtle::CtOption"]
def subtle.CtOption (T : Type) : Type := T × Bool
