/-
Primality of the Curve25519 field prime

  q = 2^255 - 19
    = 57896044618658097711785492504343953926634992332820282019728792003956564819949

proved kernel-only (no `native_decide`, no extra axioms) via Pratt
certificates: `lucas_primality` at the 7 tree nodes

  q, p236 = 74058212732561358302231226437062788676166966415465897661863160754340907,
  75445702479781427272750846543864801, 31757755568855353,
  1919519569386763, 72106336199, 2773320623

with q - 1 = 2^2 * 3 * 65147 * p236, and `norm_num` for every prime factor
below 10^9. The modular exponentiations are computed by kernel reduction
(GMP-fast `Nat` arithmetic) of the fuel-based binary-powering function
`powMod` below.

This file is generated by tools/gen_prime25519.py from the machine-verified
certificate tools/pratt_25519.json (msieve for the 27-digit cofactor split of
p35 - 1; see tools/prime25519-certificate.md). Do not edit by hand.
-/
import Mathlib

/-! ## Kernel-computable modular exponentiation -/

namespace Helios25519Pratt

set_option maxRecDepth 8192

/-- Binary modular exponentiation, structurally recursive on `fuel` so that
the kernel can evaluate it by plain recursor reduction with GMP-fast `Nat`
operations at every step (well-founded recursion would not reduce).
Computes `a ^ e % n` whenever `e < 2 ^ fuel`. -/
def powMod : ℕ → ℕ → ℕ → ℕ → ℕ
  | 0, _, _, n => 1 % n
  | fuel + 1, a, e, n =>
    if e % 2 = 0 then
      if e = 0 then 1 % n else powMod fuel (a * a % n) (e / 2) n
    else
      powMod fuel (a * a % n) (e / 2) n * a % n

theorem powMod_eq (fuel : ℕ) :
    ∀ a e n : ℕ, e < 2 ^ fuel → powMod fuel a e n = a ^ e % n := by
  induction fuel with
  | zero =>
    intro a e n h
    have he : e = 0 := by simpa using Nat.lt_one_iff.mp (by simpa using h)
    subst he
    simp [powMod]
  | succ fuel ih =>
    intro a e n h
    have h2 : e / 2 < 2 ^ fuel := by
      have hp : 2 ^ (fuel + 1) = 2 ^ fuel * 2 := pow_succ 2 fuel
      omega
    rw [powMod]
    by_cases hp : e % 2 = 0
    · rw [if_pos hp]
      by_cases he : e = 0
      · subst he; simp
      · rw [if_neg he, ih _ _ _ h2, ← Nat.pow_mod, ← pow_two, ← pow_mul]
        have hee : 2 * (e / 2) = e := by omega
        rw [hee]
    · rw [if_neg hp, ih _ _ _ h2, ← Nat.pow_mod, ← pow_two, ← pow_mul,
        Nat.mod_mul_mod, ← pow_succ]
      have hee : 2 * (e / 2) + 1 = e := by omega
      rw [hee]

theorem pow_mod_eq_of_powMod (fuel a e n r : ℕ) (hb : e < 2 ^ fuel)
    (h : powMod fuel a e n = r) : a ^ e % n = r :=
  (powMod_eq fuel a e n hb).symm.trans h

/-! ## Bridging `ℕ` congruences to `ZMod` power equations -/

theorem zmod_pow_eq (n w e r : ℕ) (h : w ^ e % n = r) :
    (w : ZMod n) ^ e = (r : ZMod n) := by
  calc (w : ZMod n) ^ e = ((w ^ e : ℕ) : ZMod n) := by rw [Nat.cast_pow]
    _ = ((w ^ e % n : ℕ) : ZMod n) := (ZMod.natCast_mod _ _).symm
    _ = (r : ZMod n) := by rw [h]

theorem zmod_pow_eq_one (n w e : ℕ) (h : w ^ e % n = 1) :
    (w : ZMod n) ^ e = 1 := by
  simpa using zmod_pow_eq n w e 1 h

theorem zmod_pow_ne_one (n w e r : ℕ) (hn : 1 < n) (hr : r ≠ 1)
    (h : w ^ e % n = r) : (w : ZMod n) ^ e ≠ 1 := by
  haveI : NeZero n := ⟨by omega⟩
  have hrn : r < n := h ▸ Nat.mod_lt _ (by omega)
  rw [zmod_pow_eq n w e r h]
  intro hc
  have hv := congrArg ZMod.val hc
  rw [ZMod.val_cast_of_lt hrn, ZMod.val_one_eq_one_mod, Nat.mod_eq_of_lt hn] at hv
  exact hr hv

/-! ## Pratt certificate nodes (bottom-up) -/

theorem prime_2773320623 : Nat.Prime 2773320623 := by
  have hb : (2773320623 : ℕ) - 1 < 2 ^ 256 := by norm_num
  have hn : (1 : ℕ) < 2773320623 := by norm_num
  refine lucas_primality _ ((5 : ℕ) : ZMod 2773320623) ?_ ?_
  · refine zmod_pow_eq_one _ 5 _ (pow_mod_eq_of_powMod 256 5 _ _ 1 hb ?_)
    rfl
  · intro q hq hdvd
    have hfac : (2773320623 : ℕ) - 1 = 2 * (2437 * (569003)) := by norm_num
    rw [hfac] at hdvd
    rcases (Nat.Prime.dvd_mul hq).mp hdvd with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
      refine zmod_pow_ne_one _ 5 _ 2773320622 hn (by norm_num)
        (pow_mod_eq_of_powMod 256 5 _ _ _
          (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
      rfl
    · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
        refine zmod_pow_ne_one _ 5 _ 844634197 hn (by norm_num)
          (pow_mod_eq_of_powMod 256 5 _ _ _
            (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
        rfl
      · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
        refine zmod_pow_ne_one _ 5 _ 2420059583 hn (by norm_num)
          (pow_mod_eq_of_powMod 256 5 _ _ _
            (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
        rfl

theorem prime_72106336199 : Nat.Prime 72106336199 := by
  have hb : (72106336199 : ℕ) - 1 < 2 ^ 256 := by norm_num
  have hn : (1 : ℕ) < 72106336199 := by norm_num
  refine lucas_primality _ ((7 : ℕ) : ZMod 72106336199) ?_ ?_
  · refine zmod_pow_eq_one _ 7 _ (pow_mod_eq_of_powMod 256 7 _ _ 1 hb ?_)
    rfl
  · intro q hq hdvd
    have hfac : (72106336199 : ℕ) - 1 = 2 * (13 * (2773320623)) := by norm_num
    rw [hfac] at hdvd
    rcases (Nat.Prime.dvd_mul hq).mp hdvd with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
      refine zmod_pow_ne_one _ 7 _ 72106336198 hn (by norm_num)
        (pow_mod_eq_of_powMod 256 7 _ _ _
          (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
      rfl
    · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
        refine zmod_pow_ne_one _ 7 _ 58700762603 hn (by norm_num)
          (pow_mod_eq_of_powMod 256 7 _ _ _
            (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
        rfl
      · rw [(Nat.prime_dvd_prime_iff_eq hq prime_2773320623).mp h]
        refine zmod_pow_ne_one _ 7 _ 28357292573 hn (by norm_num)
          (pow_mod_eq_of_powMod 256 7 _ _ _
            (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
        rfl

theorem prime_1919519569386763 : Nat.Prime 1919519569386763 := by
  have hb : (1919519569386763 : ℕ) - 1 < 2 ^ 256 := by norm_num
  have hn : (1 : ℕ) < 1919519569386763 := by norm_num
  refine lucas_primality _ ((2 : ℕ) : ZMod 1919519569386763) ?_ ?_
  · refine zmod_pow_eq_one _ 2 _ (pow_mod_eq_of_powMod 256 2 _ _ 1 hb ?_)
    rfl
  · intro q hq hdvd
    have hfac : (1919519569386763 : ℕ) - 1 = 2 * (3 * (7 * (19 * (47 ^ 2 * (127 * (8574133)))))) := by norm_num
    rw [hfac] at hdvd
    rcases (Nat.Prime.dvd_mul hq).mp hdvd with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
      refine zmod_pow_ne_one _ 2 _ 1919519569386762 hn (by norm_num)
        (pow_mod_eq_of_powMod 256 2 _ _ _
          (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
      rfl
    · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
        refine zmod_pow_ne_one _ 2 _ 1786118255295340 hn (by norm_num)
          (pow_mod_eq_of_powMod 256 2 _ _ _
            (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
        rfl
      · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
        · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
          refine zmod_pow_ne_one _ 2 _ 1124719358789780 hn (by norm_num)
            (pow_mod_eq_of_powMod 256 2 _ _ _
              (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
          rfl
        · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
          · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
            refine zmod_pow_ne_one _ 2 _ 602275051902557 hn (by norm_num)
              (pow_mod_eq_of_powMod 256 2 _ _ _
                (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
            rfl
          · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
            · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp (hq.dvd_of_dvd_pow h)]
              refine zmod_pow_ne_one _ 2 _ 621931926534591 hn (by norm_num)
                (pow_mod_eq_of_powMod 256 2 _ _ _
                  (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
              rfl
            · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
              · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
                refine zmod_pow_ne_one _ 2 _ 576774792492622 hn (by norm_num)
                  (pow_mod_eq_of_powMod 256 2 _ _ _
                    (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
                rfl
              · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
                refine zmod_pow_ne_one _ 2 _ 1059928654987441 hn (by norm_num)
                  (pow_mod_eq_of_powMod 256 2 _ _ _
                    (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
                rfl

theorem prime_31757755568855353 : Nat.Prime 31757755568855353 := by
  have hb : (31757755568855353 : ℕ) - 1 < 2 ^ 256 := by norm_num
  have hn : (1 : ℕ) < 31757755568855353 := by norm_num
  refine lucas_primality _ ((10 : ℕ) : ZMod 31757755568855353) ?_ ?_
  · refine zmod_pow_eq_one _ 10 _ (pow_mod_eq_of_powMod 256 10 _ _ 1 hb ?_)
    rfl
  · intro q hq hdvd
    have hfac : (31757755568855353 : ℕ) - 1 = 2 ^ 3 * (3 * (31 * (107 * (223 * (4153 * (430751)))))) := by norm_num
    rw [hfac] at hdvd
    rcases (Nat.Prime.dvd_mul hq).mp hdvd with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp (hq.dvd_of_dvd_pow h)]
      refine zmod_pow_ne_one _ 10 _ 31757755568855352 hn (by norm_num)
        (pow_mod_eq_of_powMod 256 10 _ _ _
          (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
      rfl
    · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
        refine zmod_pow_ne_one _ 10 _ 22133410514677784 hn (by norm_num)
          (pow_mod_eq_of_powMod 256 10 _ _ _
            (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
        rfl
      · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
        · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
          refine zmod_pow_ne_one _ 10 _ 24776906756080210 hn (by norm_num)
            (pow_mod_eq_of_powMod 256 10 _ _ _
              (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
          rfl
        · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
          · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
            refine zmod_pow_ne_one _ 10 _ 30702321360579269 hn (by norm_num)
              (pow_mod_eq_of_powMod 256 10 _ _ _
                (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
            rfl
          · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
            · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
              refine zmod_pow_ne_one _ 10 _ 5141820974828509 hn (by norm_num)
                (pow_mod_eq_of_powMod 256 10 _ _ _
                  (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
              rfl
            · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
              · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
                refine zmod_pow_ne_one _ 10 _ 29494927157741833 hn (by norm_num)
                  (pow_mod_eq_of_powMod 256 10 _ _ _
                    (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
                rfl
              · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
                refine zmod_pow_ne_one _ 10 _ 25185179080663893 hn (by norm_num)
                  (pow_mod_eq_of_powMod 256 10 _ _ _
                    (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
                rfl

theorem prime_75445702479781427272750846543864801 : Nat.Prime 75445702479781427272750846543864801 := by
  have hb : (75445702479781427272750846543864801 : ℕ) - 1 < 2 ^ 256 := by norm_num
  have hn : (1 : ℕ) < 75445702479781427272750846543864801 := by norm_num
  refine lucas_primality _ ((7 : ℕ) : ZMod 75445702479781427272750846543864801) ?_ ?_
  · refine zmod_pow_eq_one _ 7 _ (pow_mod_eq_of_powMod 256 7 _ _ 1 hb ?_)
    rfl
  · intro q hq hdvd
    have hfac : (75445702479781427272750846543864801 : ℕ) - 1 = 2 ^ 5 * (3 ^ 2 * (5 ^ 2 * (75707 * (72106336199 * (1919519569386763))))) := by norm_num
    rw [hfac] at hdvd
    rcases (Nat.Prime.dvd_mul hq).mp hdvd with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp (hq.dvd_of_dvd_pow h)]
      refine zmod_pow_ne_one _ 7 _ 75445702479781427272750846543864800 hn (by norm_num)
        (pow_mod_eq_of_powMod 256 7 _ _ _
          (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
      rfl
    · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp (hq.dvd_of_dvd_pow h)]
        refine zmod_pow_ne_one _ 7 _ 17027744575660264744512945715121884 hn (by norm_num)
          (pow_mod_eq_of_powMod 256 7 _ _ _
            (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
        rfl
      · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
        · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp (hq.dvd_of_dvd_pow h)]
          refine zmod_pow_ne_one _ 7 _ 52755092631156469601217826477970212 hn (by norm_num)
            (pow_mod_eq_of_powMod 256 7 _ _ _
              (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
          rfl
        · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
          · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
            refine zmod_pow_ne_one _ 7 _ 57103426308028043857659793617446015 hn (by norm_num)
              (pow_mod_eq_of_powMod 256 7 _ _ _
                (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
            rfl
          · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
            · rw [(Nat.prime_dvd_prime_iff_eq hq prime_72106336199).mp h]
              refine zmod_pow_ne_one _ 7 _ 72344277920069036431504068385047591 hn (by norm_num)
                (pow_mod_eq_of_powMod 256 7 _ _ _
                  (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
              rfl
            · rw [(Nat.prime_dvd_prime_iff_eq hq prime_1919519569386763).mp h]
              refine zmod_pow_ne_one _ 7 _ 33763476511538335360127990623883028 hn (by norm_num)
                (pow_mod_eq_of_powMod 256 7 _ _ _
                  (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
              rfl

theorem prime_74058212732561358302231226437062788676166966415465897661863160754340907 : Nat.Prime 74058212732561358302231226437062788676166966415465897661863160754340907 := by
  have hb : (74058212732561358302231226437062788676166966415465897661863160754340907 : ℕ) - 1 < 2 ^ 256 := by norm_num
  have hn : (1 : ℕ) < 74058212732561358302231226437062788676166966415465897661863160754340907 := by norm_num
  refine lucas_primality _ ((2 : ℕ) : ZMod 74058212732561358302231226437062788676166966415465897661863160754340907) ?_ ?_
  · refine zmod_pow_eq_one _ 2 _ (pow_mod_eq_of_powMod 256 2 _ _ 1 hb ?_)
    rfl
  · intro q hq hdvd
    have hfac : (74058212732561358302231226437062788676166966415465897661863160754340907 : ℕ) - 1 = 2 * (3 * (353 * (57467 * (132049 * (1923133 * (31757755568855353 * (75445702479781427272750846543864801))))))) := by norm_num
    rw [hfac] at hdvd
    rcases (Nat.Prime.dvd_mul hq).mp hdvd with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
      refine zmod_pow_ne_one _ 2 _ 74058212732561358302231226437062788676166966415465897661863160754340906 hn (by norm_num)
        (pow_mod_eq_of_powMod 256 2 _ _ _
          (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
      rfl
    · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
        refine zmod_pow_ne_one _ 2 _ 30397109428614726089754189191956088611235801571633239974164411255784155 hn (by norm_num)
          (pow_mod_eq_of_powMod 256 2 _ _ _
            (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
        rfl
      · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
        · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
          refine zmod_pow_ne_one _ 2 _ 8562916886866218785688304546164188478888058893729309188831496247839076 hn (by norm_num)
            (pow_mod_eq_of_powMod 256 2 _ _ _
              (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
          rfl
        · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
          · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
            refine zmod_pow_ne_one _ 2 _ 34423717228876157273670922671787235583289084632054732964365754153055025 hn (by norm_num)
              (pow_mod_eq_of_powMod 256 2 _ _ _
                (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
            rfl
          · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
            · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
              refine zmod_pow_ne_one _ 2 _ 54871647690314810166557542068595163151590274869528630571075996285882505 hn (by norm_num)
                (pow_mod_eq_of_powMod 256 2 _ _ _
                  (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
              rfl
            · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
              · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
                refine zmod_pow_ne_one _ 2 _ 52266576830164329332527201090776533817489900267135412990654516667243924 hn (by norm_num)
                  (pow_mod_eq_of_powMod 256 2 _ _ _
                    (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
                rfl
              · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
                · rw [(Nat.prime_dvd_prime_iff_eq hq prime_31757755568855353).mp h]
                  refine zmod_pow_ne_one _ 2 _ 50366660687963342066214195241331738400016478712605795091965648721912165 hn (by norm_num)
                    (pow_mod_eq_of_powMod 256 2 _ _ _
                      (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
                  rfl
                · rw [(Nat.prime_dvd_prime_iff_eq hq prime_75445702479781427272750846543864801).mp h]
                  refine zmod_pow_ne_one _ 2 _ 69490809710348678725736597923071784769591275419387514694139338586948360 hn (by norm_num)
                    (pow_mod_eq_of_powMod 256 2 _ _ _
                      (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
                  rfl

theorem prime_57896044618658097711785492504343953926634992332820282019728792003956564819949 : Nat.Prime 57896044618658097711785492504343953926634992332820282019728792003956564819949 := by
  have hb : (57896044618658097711785492504343953926634992332820282019728792003956564819949 : ℕ) - 1 < 2 ^ 256 := by norm_num
  have hn : (1 : ℕ) < 57896044618658097711785492504343953926634992332820282019728792003956564819949 := by norm_num
  refine lucas_primality _ ((2 : ℕ) : ZMod 57896044618658097711785492504343953926634992332820282019728792003956564819949) ?_ ?_
  · refine zmod_pow_eq_one _ 2 _ (pow_mod_eq_of_powMod 256 2 _ _ 1 hb ?_)
    rfl
  · intro q hq hdvd
    have hfac : (57896044618658097711785492504343953926634992332820282019728792003956564819949 : ℕ) - 1 = 2 ^ 2 * (3 * (65147 * (74058212732561358302231226437062788676166966415465897661863160754340907))) := by norm_num
    rw [hfac] at hdvd
    rcases (Nat.Prime.dvd_mul hq).mp hdvd with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp (hq.dvd_of_dvd_pow h)]
      refine zmod_pow_ne_one _ 2 _ 57896044618658097711785492504343953926634992332820282019728792003956564819948 hn (by norm_num)
        (pow_mod_eq_of_powMod 256 2 _ _ _
          (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
      rfl
    · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
        refine zmod_pow_ne_one _ 2 _ 25380276437079137597092236364571181010632177832931468165172742469126098314552 hn (by norm_num)
          (pow_mod_eq_of_powMod 256 2 _ _ _
            (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
        rfl
      · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
        · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
          refine zmod_pow_ne_one _ 2 _ 22602559476203468486837656474023958799180643873278202064348025470901666305470 hn (by norm_num)
            (pow_mod_eq_of_powMod 256 2 _ _ _
              (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
          rfl
        · rw [(Nat.prime_dvd_prime_iff_eq hq prime_74058212732561358302231226437062788676166966415465897661863160754340907).mp h]
          refine zmod_pow_ne_one _ 2 _ 427094198651976259540344842774561673889945192655078505504941250475370961481 hn (by norm_num)
            (pow_mod_eq_of_powMod 256 2 _ _ _
              (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
          rfl


end Helios25519Pratt

/-- **The Curve25519 field prime is prime.**
`q = 2^255 - 19`, the base field of Curve25519/Ed25519 and the field the
Helios/Selene tower cycle sits over. Kernel-only Pratt-certificate proof;
depends on no axioms beyond `propext`, `Classical.choice`, `Quot.sound`. -/
theorem q_prime :
    Nat.Prime
      57896044618658097711785492504343953926634992332820282019728792003956564819949 :=
  Helios25519Pratt.prime_57896044618658097711785492504343953926634992332820282019728792003956564819949

instance fact_q_prime :
    Fact (Nat.Prime
      57896044618658097711785492504343953926634992332820282019728792003956564819949) :=
  ⟨q_prime⟩
