/-
Primality of the helioselene prime

  p = 2^255 - 0x8cab7e2e6960ce8067af49720ee20ad
    = 57896044618658097711785492504343953926623305935230693509004809574567321395027

proved kernel-only (no `native_decide`, no extra axioms) via Pratt
certificates: `lucas_primality` at the 7 tree nodes

  p, p36 = 534841956073462850512095405427775209,
  p37 = 7264050700998174191624543895013716307, 2611669708609136013927259,
  32182309259467, 5062387142597, 4508463343

with p - 1 = 2 * 7451 * p36 * p37, and `norm_num` for every prime factor
below 10^9. The modular exponentiations are computed by kernel reduction
(GMP-fast `Nat` arithmetic) of the fuel-based binary-powering function
`powMod` below.

This file is generated by gen_prime.py (phase-c scratchpad); the certificate
data was found and machine-verified separately (msieve for the 73-digit
cofactor split; see phase-a/prime-certificate.md). Do not edit by hand.
-/
import Mathlib

/-! ## Kernel-computable modular exponentiation -/

namespace HelioselenePratt

set_option maxRecDepth 8192

/-- Binary modular exponentiation, structurally recursive on `fuel` so that
the kernel can evaluate it by plain recursor reduction with GMP-fast `Nat`
operations at every step (well-founded recursion would not reduce).
Computes `a ^ e % n` whenever `e < 2 ^ fuel`. -/
def powMod : ℕ → ℕ → ℕ → ℕ → ℕ
  | 0, _, _, n => 1 % n
  | fuel + 1, a, e, n =>
    if e % 2 = 0 then
      if e = 0 then 1 % n else powMod fuel (a * a % n) (e / 2) n
    else
      powMod fuel (a * a % n) (e / 2) n * a % n

theorem powMod_eq (fuel : ℕ) :
    ∀ a e n : ℕ, e < 2 ^ fuel → powMod fuel a e n = a ^ e % n := by
  induction fuel with
  | zero =>
    intro a e n h
    have he : e = 0 := by simpa using Nat.lt_one_iff.mp (by simpa using h)
    subst he
    simp [powMod]
  | succ fuel ih =>
    intro a e n h
    have h2 : e / 2 < 2 ^ fuel := by
      have hp : 2 ^ (fuel + 1) = 2 ^ fuel * 2 := pow_succ 2 fuel
      omega
    rw [powMod]
    by_cases hp : e % 2 = 0
    · rw [if_pos hp]
      by_cases he : e = 0
      · subst he; simp
      · rw [if_neg he, ih _ _ _ h2, ← Nat.pow_mod, ← pow_two, ← pow_mul]
        have hee : 2 * (e / 2) = e := by omega
        rw [hee]
    · rw [if_neg hp, ih _ _ _ h2, ← Nat.pow_mod, ← pow_two, ← pow_mul,
        Nat.mod_mul_mod, ← pow_succ]
      have hee : 2 * (e / 2) + 1 = e := by omega
      rw [hee]

theorem pow_mod_eq_of_powMod (fuel a e n r : ℕ) (hb : e < 2 ^ fuel)
    (h : powMod fuel a e n = r) : a ^ e % n = r :=
  (powMod_eq fuel a e n hb).symm.trans h

/-! ## Bridging `ℕ` congruences to `ZMod` power equations -/

theorem zmod_pow_eq (n w e r : ℕ) (h : w ^ e % n = r) :
    (w : ZMod n) ^ e = (r : ZMod n) := by
  calc (w : ZMod n) ^ e = ((w ^ e : ℕ) : ZMod n) := by rw [Nat.cast_pow]
    _ = ((w ^ e % n : ℕ) : ZMod n) := (ZMod.natCast_mod _ _).symm
    _ = (r : ZMod n) := by rw [h]

theorem zmod_pow_eq_one (n w e : ℕ) (h : w ^ e % n = 1) :
    (w : ZMod n) ^ e = 1 := by
  simpa using zmod_pow_eq n w e 1 h

theorem zmod_pow_ne_one (n w e r : ℕ) (hn : 1 < n) (hr : r ≠ 1)
    (h : w ^ e % n = r) : (w : ZMod n) ^ e ≠ 1 := by
  haveI : NeZero n := ⟨by omega⟩
  have hrn : r < n := h ▸ Nat.mod_lt _ (by omega)
  rw [zmod_pow_eq n w e r h]
  intro hc
  have hv := congrArg ZMod.val hc
  rw [ZMod.val_cast_of_lt hrn, ZMod.val_one_eq_one_mod, Nat.mod_eq_of_lt hn] at hv
  exact hr hv

/-! ## Pratt certificate nodes (bottom-up) -/

theorem prime_4508463343 : Nat.Prime 4508463343 := by
  have hb : (4508463343 : ℕ) - 1 < 2 ^ 256 := by norm_num
  have hn : (1 : ℕ) < 4508463343 := by norm_num
  refine lucas_primality _ ((5 : ℕ) : ZMod 4508463343) ?_ ?_
  · refine zmod_pow_eq_one _ 5 _ (pow_mod_eq_of_powMod 256 5 _ _ 1 hb ?_)
    rfl
  · intro q hq hdvd
    have hfac : (4508463343 : ℕ) - 1 = 2 * (3 * (17 * (673 * (65677)))) := by norm_num
    rw [hfac] at hdvd
    rcases (Nat.Prime.dvd_mul hq).mp hdvd with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
      refine zmod_pow_ne_one _ 5 _ 4508463342 hn (by norm_num)
        (pow_mod_eq_of_powMod 256 5 _ _ _
          (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
      rfl
    · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
        refine zmod_pow_ne_one _ 5 _ 416184978 hn (by norm_num)
          (pow_mod_eq_of_powMod 256 5 _ _ _
            (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
        rfl
      · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
        · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
          refine zmod_pow_ne_one _ 5 _ 3420135715 hn (by norm_num)
            (pow_mod_eq_of_powMod 256 5 _ _ _
              (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
          rfl
        · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
          · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
            refine zmod_pow_ne_one _ 5 _ 293516159 hn (by norm_num)
              (pow_mod_eq_of_powMod 256 5 _ _ _
                (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
            rfl
          · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
            refine zmod_pow_ne_one _ 5 _ 985682396 hn (by norm_num)
              (pow_mod_eq_of_powMod 256 5 _ _ _
                (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
            rfl

theorem prime_5062387142597 : Nat.Prime 5062387142597 := by
  have hb : (5062387142597 : ℕ) - 1 < 2 ^ 256 := by norm_num
  have hn : (1 : ℕ) < 5062387142597 := by norm_num
  refine lucas_primality _ ((2 : ℕ) : ZMod 5062387142597) ?_ ?_
  · refine zmod_pow_eq_one _ 2 _ (pow_mod_eq_of_powMod 256 2 _ _ 1 hb ?_)
    rfl
  · intro q hq hdvd
    have hfac : (5062387142597 : ℕ) - 1 = 2 ^ 2 * (7 * (20269 * (8920003))) := by norm_num
    rw [hfac] at hdvd
    rcases (Nat.Prime.dvd_mul hq).mp hdvd with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp (hq.dvd_of_dvd_pow h)]
      refine zmod_pow_ne_one _ 2 _ 5062387142596 hn (by norm_num)
        (pow_mod_eq_of_powMod 256 2 _ _ _
          (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
      rfl
    · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
        refine zmod_pow_ne_one _ 2 _ 3774051485773 hn (by norm_num)
          (pow_mod_eq_of_powMod 256 2 _ _ _
            (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
        rfl
      · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
        · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
          refine zmod_pow_ne_one _ 2 _ 406403418968 hn (by norm_num)
            (pow_mod_eq_of_powMod 256 2 _ _ _
              (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
          rfl
        · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
          refine zmod_pow_ne_one _ 2 _ 346520826010 hn (by norm_num)
            (pow_mod_eq_of_powMod 256 2 _ _ _
              (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
          rfl

theorem prime_32182309259467 : Nat.Prime 32182309259467 := by
  have hb : (32182309259467 : ℕ) - 1 < 2 ^ 256 := by norm_num
  have hn : (1 : ℕ) < 32182309259467 := by norm_num
  refine lucas_primality _ ((2 : ℕ) : ZMod 32182309259467) ?_ ?_
  · refine zmod_pow_eq_one _ 2 _ (pow_mod_eq_of_powMod 256 2 _ _ 1 hb ?_)
    rfl
  · intro q hq hdvd
    have hfac : (32182309259467 : ℕ) - 1 = 2 * (3 * (15373 * (348905107))) := by norm_num
    rw [hfac] at hdvd
    rcases (Nat.Prime.dvd_mul hq).mp hdvd with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
      refine zmod_pow_ne_one _ 2 _ 32182309259466 hn (by norm_num)
        (pow_mod_eq_of_powMod 256 2 _ _ _
          (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
      rfl
    · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
        refine zmod_pow_ne_one _ 2 _ 6217649135407 hn (by norm_num)
          (pow_mod_eq_of_powMod 256 2 _ _ _
            (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
        rfl
      · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
        · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
          refine zmod_pow_ne_one _ 2 _ 29297391402241 hn (by norm_num)
            (pow_mod_eq_of_powMod 256 2 _ _ _
              (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
          rfl
        · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
          refine zmod_pow_ne_one _ 2 _ 13983922352098 hn (by norm_num)
            (pow_mod_eq_of_powMod 256 2 _ _ _
              (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
          rfl

theorem prime_2611669708609136013927259 : Nat.Prime 2611669708609136013927259 := by
  have hb : (2611669708609136013927259 : ℕ) - 1 < 2 ^ 256 := by norm_num
  have hn : (1 : ℕ) < 2611669708609136013927259 := by norm_num
  refine lucas_primality _ ((2 : ℕ) : ZMod 2611669708609136013927259) ?_ ?_
  · refine zmod_pow_eq_one _ 2 _ (pow_mod_eq_of_powMod 256 2 _ _ 1 hb ?_)
    rfl
  · intro q hq hdvd
    have hfac : (2611669708609136013927259 : ℕ) - 1 = 2 * (3 ^ 2 * (4508463343 * (32182309259467))) := by norm_num
    rw [hfac] at hdvd
    rcases (Nat.Prime.dvd_mul hq).mp hdvd with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
      refine zmod_pow_ne_one _ 2 _ 2611669708609136013927258 hn (by norm_num)
        (pow_mod_eq_of_powMod 256 2 _ _ _
          (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
      rfl
    · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp (hq.dvd_of_dvd_pow h)]
        refine zmod_pow_ne_one _ 2 _ 459814338263718911517013 hn (by norm_num)
          (pow_mod_eq_of_powMod 256 2 _ _ _
            (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
        rfl
      · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
        · rw [(Nat.prime_dvd_prime_iff_eq hq prime_4508463343).mp h]
          refine zmod_pow_ne_one _ 2 _ 1241677938811102204065510 hn (by norm_num)
            (pow_mod_eq_of_powMod 256 2 _ _ _
              (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
          rfl
        · rw [(Nat.prime_dvd_prime_iff_eq hq prime_32182309259467).mp h]
          refine zmod_pow_ne_one _ 2 _ 2385017544998182301311731 hn (by norm_num)
            (pow_mod_eq_of_powMod 256 2 _ _ _
              (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
          rfl

theorem prime_534841956073462850512095405427775209 : Nat.Prime 534841956073462850512095405427775209 := by
  have hb : (534841956073462850512095405427775209 : ℕ) - 1 < 2 ^ 256 := by norm_num
  have hn : (1 : ℕ) < 534841956073462850512095405427775209 := by norm_num
  refine lucas_primality _ ((7 : ℕ) : ZMod 534841956073462850512095405427775209) ?_ ?_
  · refine zmod_pow_eq_one _ 7 _ (pow_mod_eq_of_powMod 256 7 _ _ 1 hb ?_)
    rfl
  · intro q hq hdvd
    have hfac : (534841956073462850512095405427775209 : ℕ) - 1 = 2 ^ 3 * (3 ^ 2 * (320657 * (23004571 * (198921971 * (5062387142597))))) := by norm_num
    rw [hfac] at hdvd
    rcases (Nat.Prime.dvd_mul hq).mp hdvd with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp (hq.dvd_of_dvd_pow h)]
      refine zmod_pow_ne_one _ 7 _ 534841956073462850512095405427775208 hn (by norm_num)
        (pow_mod_eq_of_powMod 256 7 _ _ _
          (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
      rfl
    · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp (hq.dvd_of_dvd_pow h)]
        refine zmod_pow_ne_one _ 7 _ 509510006834536688326110864679860439 hn (by norm_num)
          (pow_mod_eq_of_powMod 256 7 _ _ _
            (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
        rfl
      · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
        · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
          refine zmod_pow_ne_one _ 7 _ 346822083660476014400164477888991012 hn (by norm_num)
            (pow_mod_eq_of_powMod 256 7 _ _ _
              (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
          rfl
        · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
          · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
            refine zmod_pow_ne_one _ 7 _ 332061037775022386749592317225813911 hn (by norm_num)
              (pow_mod_eq_of_powMod 256 7 _ _ _
                (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
            rfl
          · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
            · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
              refine zmod_pow_ne_one _ 7 _ 516804694523521634707119545267813576 hn (by norm_num)
                (pow_mod_eq_of_powMod 256 7 _ _ _
                  (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
              rfl
            · rw [(Nat.prime_dvd_prime_iff_eq hq prime_5062387142597).mp h]
              refine zmod_pow_ne_one _ 7 _ 302001981512948022743802476876493741 hn (by norm_num)
                (pow_mod_eq_of_powMod 256 7 _ _ _
                  (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
              rfl

theorem prime_7264050700998174191624543895013716307 : Nat.Prime 7264050700998174191624543895013716307 := by
  have hb : (7264050700998174191624543895013716307 : ℕ) - 1 < 2 ^ 256 := by norm_num
  have hn : (1 : ℕ) < 7264050700998174191624543895013716307 := by norm_num
  refine lucas_primality _ ((5 : ℕ) : ZMod 7264050700998174191624543895013716307) ?_ ?_
  · refine zmod_pow_eq_one _ 5 _ (pow_mod_eq_of_powMod 256 5 _ _ 1 hb ?_)
    rfl
  · intro q hq hdvd
    have hfac : (7264050700998174191624543895013716307 : ℕ) - 1 = 2 * (3 ^ 4 * (11 * (17 * (91812961 * (2611669708609136013927259))))) := by norm_num
    rw [hfac] at hdvd
    rcases (Nat.Prime.dvd_mul hq).mp hdvd with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
      refine zmod_pow_ne_one _ 5 _ 7264050700998174191624543895013716306 hn (by norm_num)
        (pow_mod_eq_of_powMod 256 5 _ _ _
          (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
      rfl
    · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp (hq.dvd_of_dvd_pow h)]
        refine zmod_pow_ne_one _ 5 _ 624993299421224043733287904127652359 hn (by norm_num)
          (pow_mod_eq_of_powMod 256 5 _ _ _
            (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
        rfl
      · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
        · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
          refine zmod_pow_ne_one _ 5 _ 5885655933121902142480117741463985754 hn (by norm_num)
            (pow_mod_eq_of_powMod 256 5 _ _ _
              (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
          rfl
        · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
          · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
            refine zmod_pow_ne_one _ 5 _ 1149398037581860107235553048273350504 hn (by norm_num)
              (pow_mod_eq_of_powMod 256 5 _ _ _
                (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
            rfl
          · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
            · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
              refine zmod_pow_ne_one _ 5 _ 1291517824372760508428748261997155693 hn (by norm_num)
                (pow_mod_eq_of_powMod 256 5 _ _ _
                  (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
              rfl
            · rw [(Nat.prime_dvd_prime_iff_eq hq prime_2611669708609136013927259).mp h]
              refine zmod_pow_ne_one _ 5 _ 4445251633365267266907512869965126475 hn (by norm_num)
                (pow_mod_eq_of_powMod 256 5 _ _ _
                  (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
              rfl

theorem prime_57896044618658097711785492504343953926623305935230693509004809574567321395027 : Nat.Prime 57896044618658097711785492504343953926623305935230693509004809574567321395027 := by
  have hb : (57896044618658097711785492504343953926623305935230693509004809574567321395027 : ℕ) - 1 < 2 ^ 256 := by norm_num
  have hn : (1 : ℕ) < 57896044618658097711785492504343953926623305935230693509004809574567321395027 := by norm_num
  refine lucas_primality _ ((2 : ℕ) : ZMod 57896044618658097711785492504343953926623305935230693509004809574567321395027) ?_ ?_
  · refine zmod_pow_eq_one _ 2 _ (pow_mod_eq_of_powMod 256 2 _ _ 1 hb ?_)
    rfl
  · intro q hq hdvd
    have hfac : (57896044618658097711785492504343953926623305935230693509004809574567321395027 : ℕ) - 1 = 2 * (7451 * (534841956073462850512095405427775209 * (7264050700998174191624543895013716307))) := by norm_num
    rw [hfac] at hdvd
    rcases (Nat.Prime.dvd_mul hq).mp hdvd with h | h
    · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
      refine zmod_pow_ne_one _ 2 _ 57896044618658097711785492504343953926623305935230693509004809574567321395026 hn (by norm_num)
        (pow_mod_eq_of_powMod 256 2 _ _ _
          (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
      rfl
    · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
      · rw [(Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp h]
        refine zmod_pow_ne_one _ 2 _ 12549742139423458495931974957820635032925102480405042027582823808914668999823 hn (by norm_num)
          (pow_mod_eq_of_powMod 256 2 _ _ _
            (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
        rfl
      · rcases (Nat.Prime.dvd_mul hq).mp h with h | h
        · rw [(Nat.prime_dvd_prime_iff_eq hq prime_534841956073462850512095405427775209).mp h]
          refine zmod_pow_ne_one _ 2 _ 17131695357584651296710375216979073178366564144091740154019600692697082213660 hn (by norm_num)
            (pow_mod_eq_of_powMod 256 2 _ _ _
              (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
          rfl
        · rw [(Nat.prime_dvd_prime_iff_eq hq prime_7264050700998174191624543895013716307).mp h]
          refine zmod_pow_ne_one _ 2 _ 26631637731688310792015055264847790470577755348044071852823383762362940403942 hn (by norm_num)
            (pow_mod_eq_of_powMod 256 2 _ _ _
              (Nat.lt_of_le_of_lt (Nat.div_le_self _ _) hb) ?_)
          rfl


end HelioselenePratt

/-- **The helioselene prime is prime.**
`p = 2^255 - 0x8cab7e2e6960ce8067af49720ee20ad`, the base field of the Selene
curve and scalar field of the Helios curve. Kernel-only Pratt-certificate
proof; depends on no axioms beyond `propext`, `Classical.choice`,
`Quot.sound`. -/
theorem p_prime :
    Nat.Prime
      57896044618658097711785492504343953926623305935230693509004809574567321395027 :=
  HelioselenePratt.prime_57896044618658097711785492504343953926623305935230693509004809574567321395027

instance fact_p_prime :
    Fact (Nat.Prime
      57896044618658097711785492504343953926623305935230693509004809574567321395027) :=
  ⟨p_prime⟩
